### ISSUE TITLE
Annotations not showing up in aggregations but labels are

### ISSUE THREAD

**Issue by sumanmukherjee03** [kubecost/cost-analyzer-helm-chart#1644] opened 2022-08-18 23:18 UTC
**Describe the bug**
Controller objects with annotations not showing up in aggregations in the UI but one that are labeled are showing up

**To Reproduce**
I am using chart version 1.96.0.
I have this relevant config in my kustomize `values.yaml`

```
kubecostMetrics:
  emitPodAnnotations: true
  emitNamespaceAnnotations: true
  emitKsmV1Metrics: true
  emitKsmV1MetricsOnly: false
  exporter:
    enabled: false

...

kubecostProductConfigs:
  currencyCode: "USD"
  labelMappingConfigs:
    enabled: true
    owner_label: "example_com_project"
    team_label: "example_com_service_owner"
    product_label: "app_kubernetes_io_name"
    owner_external_label: "example_com_project"
    team_external_label: "example_com_service_owner"
    product_external_label: "app_kubernetes_io_name"
```

I have some statefulsets with owner label `example.com/project` and some other statefulsets with annotations  `example.com/project`. The pods in the statefulsets are also labeled and annotated accordingly, because I am using `commonLabels` and `commonAnnotations` in kustomize.

In the UI when i select aggregation by "Owner", I was expecting to see all the statefulsets which are labeled as well as annotated. However, I am only seeing the ones with the label. The ones with annotation are not showing up in the aggregate. Same behavior when I use filter in the UI. Also, this seems to be the case for aggregations other than just owner, ie, same behavior for product etc.

**Expected behavior**
I was expecting to see all the statefulsets which are labeled as well as annotated with `example.com/project`

gz#2435<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2435'>Zendesk ticket #2435</a>)</i>

**Comment by nikovacevic** [comment] 2022-08-22 16:44
Perhaps I'm misunderstanding, but this sounds like a feature request, not a bug. I'll ask a question to clarify.

* You have some workloads with label `example.com/project` (call them workloads A), and you have other workloads with annotation `example.com/project` (call them workloads B).
* You have `owner_label` set to `example_com_project`, indicating that is the _label_ you want to use when aggregating by `owner`.
* When you aggregate by `owner` you're seeing workloads A, but not workloads B.

Is that correct? If so, then this feature is working as intended. As the configuration name `owner_label` suggests, `owner` aliases labels -- not annotations. If I am not correct, please help clarify and we can assist you.

**Comment by sumanmukherjee03** [comment] 2022-08-22 21:55
@nikovacevic that's right. That is what I am trying to achieve. I thought this https://github.com/kubecost/cost-analyzer-helm-chart/issues/1392 gave us that feature. I upgraded to 1.96.0 hoping the use case I described above to work.

May be my understanding of the feature to emit annotations is incorrect?

Attaching a screenshot of the settings page. If what i described is not a currently supported feature then we should probably fix the wording in this settings page too. It could be misleading.
![Screen Shot 2022-08-22 at 2 48 33 PM](https://user-images.githubusercontent.com/90907/186025253-d331336a-86a8-443c-9583-67d6e2e38c94.png)

**Comment by Adam-Stack-PM** [comment] 2022-08-23 21:03
@sumanmukherjee03, Routing this to our engineer on support rotation to help you on this item. They will comment soon.

**Comment by kaelanspatel** [comment] 2022-08-23 21:33
Hi @sumanmukherjee03.

If I could ask another clarifying question, for your statefulsets annotated `example.com/project` (workloads B in Niko's example above), are these also labeled with something else?

As in, you'd like to see both Workloads A (labeled with `example.com/project`) and Workloads B (annotated with `example.com/project` and labeled something else)?

**Comment by sumanmukherjee03** [comment] 2022-08-25 03:25
Hey Kaelan,

Sure. Happy to clarify further.

> for your statefulsets annotated example.com/project (workloads B in Niko's example above), are these also labeled with something else?
Yes, there are labels. Also, there are other annotations besides `example.com/project`. Workloads that have an annotation `example.com/project` do not have a label with the same name. And workloads that have a label `example.com/project` do not have annotation with the same name. But both kinds of workloads have other labels and annotations.

> As in, you'd like to see both Workloads A (labeled with example.com/project) and Workloads B (annotated with example.com/project and labeled something else)?

That is correct. We want to move away from labels towards annotations. Labels pose problems because they are immutable fields and changing their values becomes painful. But right now, we have a mix of labels and annotations for `example.com/project`.

Please let me know if there are any other clarifications needed.

**Comment by kaelanspatel** [comment] 2022-08-26 20:05
Hi @sumanmukherjee03 

That's helpful, thanks. I've taken a look at the feature and spoke with the implementing engineer. You're correct that https://github.com/kubecost/cost-analyzer-helm-chart/issues/1392 should allow you to do this, so this is definitely a bug. We will get this looked at.

Correct behavior is like you say, being able to match on both annotations and labels at the same time.

**Comment by nickcurie** [comment] 2022-08-29 20:54
Hi @sumanmukherjee03 

Could you run this query and confirm for me that you are seeing annotations under any workloads that you would expect to see annotations? `http:/localhost:9090/model/allocation?window=1h`

You should expect to see annotations under `[your allocation] > properties > annotations`.

**Comment by sumanmukherjee03** [comment] 2022-08-29 21:50
Sure. This is the relevant result from hitting the endpoint above. I assume this is what you were referring to?

FYI, there are 2 containers in the pod (mongo-primary, metrics), that's why the 2 matches.
```
"cluster-one/ip-<REDACTED>.us-west-2.compute.internal/app-microservices/<REDACTED>-mongo-primary-0/metrics": {
  "name": "cluster-one/ip-<REDACTED>.us-west-2.compute.internal/app-microservices/<REDACTED>-mongo-primary-0/metrics",
  "properties": {
    "cluster": "cluster-one",
    "node": "ip-<REDACTED>.us-west-2.compute.internal",
    "container": "metrics",
    "controller": "<REDACTED>-mongo-primary",
    "controllerKind": "statefulset",
    "namespace": "app-microservices",
    "pod": "<REDACTED>-mongo-primary-0",
    "services": [
      "<REDACTED>-mongo-headless",
      "<REDACTED>-mongo"
    ],
    "providerID": "i-INSTANCE_ID_REDACTED",
    "labels": {
      "app_kubernetes_io_name": "<REDACTED>-mongo",
      "example_com_service_owner": "<REDACTED>",
      "component": "primary",
      "controller_revision_hash": "<REDACTED>-mongo-primary-<REDACTED_COMMIT_SHA>",
      "kubernetes_io_metadata_name": "app-microservices",
      "name": "app-microservices",
      "statefulset_kubernetes_io_pod_name": "<REDACTED>-mongo-primary-0"
    },
    "annotations": {
      "example_com_project": "<REDACTED_VALUE>",
    }
  },
  "window": {
    "start": "2022-08-29T21:00:00Z",
    "end": "2022-08-29T22:00:00Z"
  },
  "start": "2022-08-29T21:00:00Z",
  "end": "2022-08-29T21:17:00Z",
  "minutes": 17,
  "cpuCores": 0,
  "cpuCoreRequestAverage": 0,
  "cpuCoreUsageAverage": 0.008872,
  "cpuCoreHours": 0,
  "cpuCost": 0,
  "cpuCostAdjustment": 0,
  "cpuEfficiency": 0,
  "gpuCount": 0,
  "gpuHours": 0,
  "gpuCost": 0,
  "gpuCostAdjustment": 0,
  "networkTransferBytes": 10764168.207376,
  "networkReceiveBytes": 9626029.594081,
  "networkCost": 0,
  "networkCostAdjustment": 0,
  "loadBalancerCost": 0,
  "loadBalancerCostAdjustment": 0,
  "pvBytes": 53687091200,
  "pvByteHours": 15211342506.666666,
  "pvCost": 0.000776,
  "pvs": null,
  "pvCostAdjustment": 0,
  "ramBytes": 2304341.333333,
  "ramByteRequestAverage": 0,
  "ramByteUsageAverage": 25985024,
  "ramByteHours": 652896.711111,
  "ramCost": 2e-06,
  "ramCostAdjustment": 0,
  "ramEfficiency": 1,
  "sharedCost": 0,
  "externalCost": 0,
  "totalCost": 0.000779,
  "totalEfficiency": 1,
  "rawAllocationOnly": {
    "cpuCoreUsageMax": 0.008871983705753842,
    "ramByteUsageMax": 27652096
  }
},

"cluster-one/ip-<REDACTED>.us-west-2.compute.internal/app-microservices/<REDACTED>-mongo-primary-0/mongo-primary": {
  "name": "cluster-one/ip-<REDACTED>.us-west-2.compute.internal/app-microservices/<REDACTED>-mongo-primary-0/mongo-primary",
  "properties": {
    "cluster": "cluster-one",
    "node": "ip-<REDACTED>.us-west-2.compute.internal",
    "container": "mongo-primary",
    "controller": "<REDACTED>-mongo-primary",
    "controllerKind": "statefulset",
    "namespace": "app-microservices",
    "pod": "<REDACTED>-mongo-primary-0",
    "services": [
      "<REDACTED>-mongo-headless",
      "<REDACTED>-mongo"
    ],
    "providerID": "i-INSTANCE_ID_REDACTED",
    "labels": {
      "app_kubernetes_io_name": "<REDACTED>-mongo",
      "example_com_service_owner": "<REDACTED>",
      "component": "primary",
      "controller_revision_hash": "<REDACTED>-mongo-primary-<REDACTED_COMMIT_SHA>",
      "kubernetes_io_metadata_name": "app-microservices",
      "name": "app-microservices",
      "statefulset_kubernetes_io_pod_name": "<REDACTED>-mongo-primary-0"
    },
    "annotations": {
      "example_com_project": "<REDACTED_VALUE>",
    }
  },
  "window": {
    "start": "2022-08-29T21:00:00Z",
    "end": "2022-08-29T22:00:00Z"
  },
  "start": "2022-08-29T21:00:00Z",
  "end": "2022-08-29T21:17:00Z",
  "minutes": 17,
  "cpuCores": 1,
  "cpuCoreRequestAverage": 1,
  "cpuCoreUsageAverage": 0.009951,
  "cpuCoreHours": 0.283333,
  "cpuCost": 0.008032,
  "cpuCostAdjustment": 0,
  "cpuEfficiency": 0.009951,
  "gpuCount": 0,
  "gpuHours": 0,
  "gpuCost": 0,
  "gpuCostAdjustment": 0,
  "networkTransferBytes": 10764168.207376,
  "networkReceiveBytes": 9626029.594081,
  "networkCost": 0,
  "networkCostAdjustment": 0,
  "loadBalancerCost": 0,
  "loadBalancerCostAdjustment": 0,
  "pvBytes": 53687091200,
  "pvByteHours": 15211342506.666666,
  "pvCost": 0.000776,
  "pvs": null,
  "pvCostAdjustment": 0,
  "ramBytes": 6442450944,
  "ramByteRequestAverage": 6442450944,
  "ramByteUsageAverage": 3638224896,
  "ramByteHours": 1825361100.8,
  "ramCost": 0.00646,
  "ramCostAdjustment": 0,
  "ramEfficiency": 0.564727,
  "sharedCost": 0,
  "externalCost": 0,
  "totalCost": 0.015268,
  "totalEfficiency": 0.257256,
  "rawAllocationOnly": {
    "cpuCoreUsageMax": 0.009950995406942548,
    "ramByteUsageMax": 3639054336
  }
}
```

**Comment by mbolt35** [comment] 2022-08-30 19:51
Just wanted to follow up here. We are still investigating.

**Comment by nickcurie** [comment] 2022-09-02 19:19
Hi @sumanmukherjee03 

We're having a bit of trouble reproducing this issue. Based on the response you've given above, it looks like the annotations are present in Kubecost's core data.

Could you run these API queries and let me know if you are seeing what you'd expect?

- `/model/allocation?aggregate=owner&window=1d&accumulate=true&filterNamespaces=app-microservices`
- `/model/allocation?aggregate=annotation:example_com_project&window=1d&accumulate=true&filterNamespaces=app-microservices`
- `/model/allocation?aggregate=label:example_com_project&window=1d&accumulate=true&filterNamespaces=app-microservices`

**Comment by sumanmukherjee03** [comment] 2022-09-03 00:47
I will get back to you with the results. In the mean time, have you considered multiple namespaces when trying to replicate the bug? May be that's something to check.

I was expecting the aggregation to work across namespaces. We have a bunch of statefulsets with the owner annotation in 1 namespace and another bunch of statefulsets with the owner label in another namespace.

**Comment by sumanmukherjee03** [comment] 2022-09-06 14:10
@nickcurie here's the information you asked for

We have a bunch of statefulsets with the owner annotation in 1 namespace and another bunch of statefulsets with the owner label in another namespace. These are the numbers for one of the namespaces where there are annotations `example_com_project` but no labels by that name on the statefulsets.
These are the queries i ran to get the numbers
```
curl "http://localhost:9090/model/allocation?aggregate=owner&window=1d&accumulate=true&filterNamespaces=app-microservices" | jq -r '.data[].<REDACTED_VALUE>'
curl "http://localhost:9090/model/allocation?aggregate=annotation:example_com_project&window=1d&accumulate=true&filterNamespaces=app-microservices" | jq -r '.data[]."example_com_project=<REDACTED_VALUE>"'
curl "http://localhost:9090/model/allocation?aggregate=label:example_com_project&window=1d&accumulate=true&filterNamespaces=app-microservices" | jq -r '.data[]."example_com_project=<REDACTED_VALUE>"'
```

And these are the relevant data
```
----------------- Aggregate by owner ------------------
{
  "name": "<REDACTED_VALUE>",
  "properties": {
    "cluster": "cluster-one",
    "namespace": "app-microservices"
  },
  "window": {
    "start": "2022-09-05T14:00:00Z",
    "end": "2022-09-06T14:00:00Z"
  },
  "minutes": 1410,
  "cpuCores": 5.5,
  "cpuCoreUsageAverage": 0.259438,
  "cpuCoreHours": 129.25,
  "cpuCost": 3.182185,
  "pvCost": 0.386301,
  "ramCost": 1.99123,
  "totalCost": 5.559716
}


----------------- Aggregate by annotations example_com_project ------------------
{
  "name": "example_com_project=<REDACTED_VALUE>",
  "properties": {
    "cluster": "cluster-one",
    "namespace": "app-microservices"
  },
  "window": {
    "start": "2022-09-05T14:00:00Z",
    "end": "2022-09-06T14:00:00Z"
  },
  "minutes": 1410,
  "cpuCores": 5.5,
  "cpuCoreUsageAverage": 0.259438,
  "cpuCoreHours": 129.25,
  "cpuCost": 3.182185,
  "pvCost": 0.386301,
  "ramCost": 1.99123,
  "totalCost": 5.559716
}



----------------- Aggregate by label example_com_project ------------------
null
```


**####################################################################**
**####################################################################**
**####################################################################**

These are the aggregations without the namespace filter.
The queries i ran to get these numbers are
```
curl "http://localhost:9090/model/allocation?aggregate=owner&window=1d&accumulate=true" | jq -r '.data[].<REDACTED_VALUE>'
curl "http://localhost:9090/model/allocation?aggregate=annotation:example_com_project&window=1d&accumulate=true" | jq -r '.data[]."example_com_project=<REDACTED_VALUE>"'
curl "http://localhost:9090/model/allocation?aggregate=label:example_com_project&window=1d&accumulate=true" | jq -r '.data[]."example_com_project=<REDACTED_VALUE>"'
```

And these are the relevant data
```
----------------- Aggregate by owner ------------------
{
  "name": "<REDACTED_VALUE>",
  "properties": {
    "cluster": "cluster-one"
  },
  "window": {
    "start": "2022-09-05T14:00:00Z",
    "end": "2022-09-06T14:00:00Z"
  },
  "minutes": 1420,
  "cpuCores": 12,
  "cpuCoreUsageAverage": 8.18214,
  "cpuCoreHours": 284,
  "cpuCost": 6.848478,
  "pvCost": 13.66831,
  "ramCost": 4.452869,
  "totalCost": 24.969657
}



----------------- Aggregate by annotations example_com_project ------------------
{
  "name": "example_com_project=<REDACTED_VALUE>",
  "properties": {
    "cluster": "cluster-one",
    "namespace": "app-microservices"
  },
  "window": {
    "start": "2022-09-05T14:00:00Z",
    "end": "2022-09-06T14:00:00Z"
  },
  "minutes": 1420,
  "cpuCores": 5.5,
  "cpuCoreUsageAverage": 0.259534,
  "cpuCoreHours": 130.166667,
  "cpuCost": 3.206166,
  "pvCost": 0.389041,
  "ramCost": 2.006085,
  "totalCost": 5.601292
}



----------------- Aggregate by label example_com_project ------------------
{
  "name": "example_com_project=<REDACTED_VALUE>",
  "properties": {
    "cluster": "cluster-one",
    "namespace": "app-microservices-support"
  },
  "window": {
    "start": "2022-09-05T14:00:00Z",
    "end": "2022-09-06T14:00:00Z"
  },
  "minutes": 1420,
  "cpuCores": 6.5,
  "cpuCoreUsageAverage": 7.922606,
  "cpuCoreHours": 153.833333,
  "cpuCost": 3.642312,
  "pvCost": 13.279269,
  "ramCost": 2.446784,
  "totalCost": 19.368365
}
```
Notice that the namespaces are different for aggregations by label and aggregation by annotation. Also, the numbers for label and annotation add up when compared with aggregation by owner.

**Comment by sumanmukherjee03** [comment] 2022-09-06 15:51
I think the bug is coming from some other queries. I looked at the queries in the UI for a page like this
![Screen Shot 2022-09-06 at 7 48 54 AM](https://user-images.githubusercontent.com/90907/188667545-00c04212-d56b-4d0e-a28e-7db977ecd89f.png)
To get to this page in the UI above, this is the series of operations i performed -
click on "Cost Allocation" > Choose single aggregation > Aggregation by owner > from the list of results click on the row of your choice > Click date range and choose 7 days > Adjust the url in the url bar to `1d` from `7d`. To me it looks like the  row with `Totals` is correct. However, it is not showing all the resources with labels/annotations.

Here are some simplified versions of the same queries via curl. I have taken out some parameters here like shared tenancy, shared namespaces etc. That's why the numbers you see in the UI screenshot wont exactly match what you see in the curl request results.

These are the curl requests
```
curl 'http://localhost:9090/model/allocation/summary?aggregate=owner&window=1d&accumulate=true' | jq -r '.data.sets[].allocations.<REDACTED_VALUE>'
curl 'http://localhost:9090/model/allocation/summary?aggregate=controller&window=1d&accumulate=true&filterOwners=<REDACTED_VALUE>' | jq -r '.data.sets[].allocations'
```

And these are the results
```
-------------------------- This is aggregate by owner --------------------------
{
  "name": "<REDACTED_VALUE>",
  "start": "2022-09-05T15:00:00Z",
  "end": "2022-09-06T14:21:00Z",
  "cpuCoreRequestAverage": 12,
  "cpuCoreUsageAverage": 8.165677124202606,
  "cpuCost": 6.806273466666667,
  "pvCost": 13.485424522680004,
  "ramCost": 4.428690223538351,
}






-------------------------- This is aggregate by controller with filter for example_com_project label/annotation value --------------------------
{
  "deployment:<REDACTED_VALUE>-proxy": {
    "name": "deployment:<REDACTED_VALUE>-proxy",
    "start": "2022-09-05T15:00:00Z",
    "end": "2022-09-06T14:21:00Z",
    "cpuCoreRequestAverage": 0.5,
    "cpuCoreUsageAverage": 1.3262584932060772,
    "cpuCost": 0.2784317416666667,
    "pvCost": 0,
    "ramCost": 0.037321383333333326
  },
  "statefulset:<REDACTED_VALUE>": {
    "name": "statefulset:<REDACTED_VALUE>",
    "start": "2022-09-05T15:00:00Z",
    "end": "2022-09-06T14:21:00Z",
    "cpuCoreRequestAverage": 6,
    "cpuCoreUsageAverage": 6.580779903440008,
    "cpuCost": 3.3463279999999993,
    "pvCost": 13.101588910080004,
    "ramCost": 2.3966786993321367
  }
}
```

The numbers from the aggregate by owner seems correct. It also lines up with the numbers from my previous comment.
However, the result from the second curl request, ie the aggregate by controller with filter by owner is wrong. It seems to be listing only the resources which have labels `example_com_project` and not the ones with the annotation. I think this is the source of the bug.

In that UI i expect to see all the resources, ie more than 2. I expect to see the statefulsets with annotations as well. Not just the ones with labels. Regardless of what namespace they live in. Since I am not filtering by namespace.

**Comment by nickcurie** [comment] 2022-09-07 19:56
Hi @sumanmukherjee03 thanks for following up. We've identified the issue and are working on a fix.

**Comment by sumanmukherjee03** [comment] 2022-09-13 17:08
@nikovacevic / @nickcurie i see this issue is marked as completed. Would you please let me know if this fix is included in `v1.97.0-rc.4` ? If not in this version, then any idea on which version it might be included in? Thanks.

**Comment by nikovacevic** [comment] 2022-09-14 19:38
Hi @sumanmukherjee03! Yes, GH automatically closed the ticket when https://github.com/kubecost/kubecost-cost-model/pull/945 was merged. That will be available in `v1.97.0`, but I'm not as certain it's available in the `rc.4`. I will look into that and let you know. `v1.97` is scheduled to be released early next week.

**Comment by nikovacevic** [comment] 2022-09-14 19:39
Looks like it is not yet in a release candidate, but it has now been merged into the `v1.97` release branch, so it will be out in the very next release.

**Comment by sumanmukherjee03** [comment] 2022-09-14 19:48
Thank you for confirming. Because I did pull the rc.4 and didnt see the fix. That's why i asked. Will wait for the release next week. Appreciate you getting back.

**Comment by sumanmukherjee03** [comment] 2022-09-23 13:01
@nikovacevic this does not appear to be fixed in `v1.97.0`.

**Comment by sumanmukherjee03** [comment] 2022-09-27 22:00
@nikovacevic / @Adam-Stack-PM i dont see this fixed in `v1.97.0`. Is the fix for this scheduled on a next release? Or does it make sense to create a new issue?

**Comment by AjayTripathy** [comment] 2022-09-27 22:14
Hi @sumanmukherjee03 I'm not immediately able to reproduce this. Can you share your configurations and the queries you're making by Owner label in v1.97?

**Comment by sumanmukherjee03** [comment] 2022-10-06 07:19
@AjayTripathy sorry it took me a while to get back to this.

Cant seem to capture bug report from the /settings page. Seeing an error in the JS console
```
Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
[asyncToGenerator.js:6:4](https://kubecost.bitgo-test.com/static/node_modules/@babel/runtime/helpers/esm/asyncToGenerator.js)
    Babel 6
    p PrometheusStatus.tsx:107
    React 11
    bind_applyFunctionN self-hosted:1683
    Ht self-hosted:1640
    React 3
    forEach self-hosted:4909
    React 2
    <anonymous> index.tsx:6
    <anonymous> index.tsx:16
    <anonymous> index.tsx:16
``` 

When you say queries, this is what I am trying to do.

Go to "Cost Allocation" > Select "Aggregate by" > Chose "Owner" from the dropdown > Click on one of the rows > I expect to see resources with tags or annotations from different namespaces for that particular value of the owner label in this page. But i only see the resources that are labeled. Not the ones that are tagged.

**Comment by AjayTripathy** [comment] 2022-10-17 17:53
Hey @nickcurie I believe you implemented this? Can you take a look during our bugfix week next week?

**Comment by sumanmukherjee03** [comment] 2022-10-20 14:48
Thanks for reopening this.

**Closed** 2022-10-27 19:07 UTC
Labels: bug, UI/UX, frontend, P1, v1.98

**Comment by nikovacevic** [comment] 2022-10-28 23:29
@sumanmukherjee03 apologies for the quick fix-and-regression here. (Not that it matters why it happened, but we initially patched a soon-to-be-deprecated code path, which was swiftly replaced with a new filtering package... that brought the bug back.)

v1.98, which we aim to release early next week, will contain the fix. Appreciate your patience, and will look forward to checking in with you after you've had a chance to upgrade and try it out.
