### ISSUE TITLE
[Bug] Account mappings values are not used

### ISSUE THREAD

**Issue by dgaffuri** [kubecost/cost-analyzer-helm-chart#3262] opened 2024-03-22 15:58 UTC
### Kubecost Helm Chart Version

2.1.2

### Kubernetes Version

1.29.1

### Kubernetes Platform

EKS

### Description

Setting kubecostProductConfigs.cloudAccountMapping has the only effect of creating the config map "account-mapping" that is not used elsewhere in the chart templates

### Steps to reproduce

1. set kubecostProductConfigs.cloudAccountMapping to `"01234567890": prod`
2. deploy the chart
3. open front end

### Expected behavior

the Cloud Costs Breakdown section shows "prod" instead of "01234567890"

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by jessegoodier** [comment] 2024-03-29 14:39
Sorry for the delay. I think we have reproduced this internally. We have internal issue filed.

We also have an issue where clicking the Cloud Account on overview is not filtered correctly on the target page.

**Comment by jessegoodier** [comment] 2024-03-29 14:39
Issue is SELFHOST-1301 for internal KC folks.

**Comment by chipzoller** [comment] 2024-05-09 14:31
From looking at this and the internal Jira, it looks like this is entirely a frontend issue and not an issue in the chart. Can you confirm? If confined to the frontend, please move to features-bugs.

**Comment by chipzoller** [comment] 2024-09-20 22:21
Listed as fixed in 2.3.3. Closing.

**Closed as completed by chipzoller** 2024-09-20 22:21 UTC
Labels: bug
