### ISSUE TITLE
Container filter is no longer avalible on Container Right Sizing page.

### ISSUE THREAD

**Issue by MikeFindsThings** [kubecost/cost-analyzer-helm-chart#2428] opened 2023-07-10 16:26 UTC
**Describe the bug**  
Previously users were able to filter the container right size page by container.

**To Reproduce**  

1. Navigate to Savings > Right-size your container requests
2. Click customize
3. Observe that Container is not an option

**Expected behavior**  
As with past versions, users should be able to filter by container

**What impact will this have on your ability to get value out of Kubecost?**
Environments might have many containers, but a user may only have control over specific containers. Being able to filter by containers allows users to get value faster by focusing on what they have control over.

**Comment by kirbsauce** [comment] 2023-07-10 16:38
@kwombach12 , confirmed that Container is not a filter option in 1.104.1.

**Comment by MikeFindsThings** [comment] 2023-07-10 16:43
For context, customer upgraded from 1.99.0 to 1.103.3. I found and provided
a work around, but it is a little cumbersome.

**Comment by kwombach12** [comment] 2023-07-10 17:01
@michaelmdresser @nealormsbee do you know if we removed the container filter for a reason?

**Comment by nealormsbee** [comment] 2023-07-10 21:18
@kwombach12 not that I'm aware of. My guess is this was dropped from the FE during recent work in that region. Very easy to put it back assuming we still have API support.

**Comment by nealormsbee** [comment] 2023-07-10 21:24
It looks like this is already present in nightly -- @MikeFindsThings @kwombach12 this should be addressed in 1.105 already.

**Comment by MikeFindsThings** [comment] 2023-07-10 23:48
Awesome! Thank you!

**Comment by nealormsbee** [comment] 2023-07-11 15:40
Sure thing! Is it alright if I close this?
For the customer's specific case...are they able to upgrade? I know in some cases they can't, but it would be nice to resolve this issue for them if possible.

**Comment by cogito-cmurphy** [comment] 2023-07-11 15:58
> Sure thing! Is it alright if I close this? For the customer's specific case...are they able to upgrade? I know in some cases they can't, but it would be nice to resolve this issue for them if possible.

When 1.105 becomes available we will upgrade. Thanks for looking into this

**Closed as completed** 2023-07-11 16:09 UTC
Labels: bug
