### ISSUE TITLE
Support views or materialized views of GCP BigQuery Data

### ISSUE THREAD

**Issue by siemenskyle** [kubecost/cost-analyzer-helm-chart#1841] opened 2022-12-07 16:26 UTC
**What problem are you trying to solve?**
Currently for GCP Biquery ingestion we are required to ingest the entire dataset of the billing export. In some cases users may want to filter the data that is exposed to opencost to only pertain to, for example, the specific cloud project that the kubernetes cluster lives in rather than every project in a billing export. This could be achieved by allowing support of a materialized view of the BQ data. 

**Describe the solution you'd like**
Currently opencost queries the dataset using the `_PARTITIONTIME` pseudocolumn that is only available to ingestion based partitioned data. As such, views or materialized views will never work if the query uses this. Modifying the query to use the `PARTITION` function instead of `_PARTITIONTIME` however could allow support for views. 

**Describe alternatives you've considered**
Creating completely separate tables that are duplicated from the bigquery billing export. Requesting that Google support multiple billing exports.

**How would users interact with this feature?**
Users could create a view such as 

```
CREATE VIEW project.billing_data.billing-view 
AS (
  SELECT
    *
  FROM
    project.billing_data.gcp_billing_export_resource_v1_ETC
  WHERE
    project.number = "1220394821"
);
```

(or alternative a materialized view that is partitioned)

Then when configuring opencost it would be provided with the `project.billing_data.billing-view`.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-222) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment] 2022-12-09 06:15
Hi @siemenskyle thanks for this feature request ,this makes sense to me. Tagging it for consideration in v1.100.

**Comment by teevans** [comment] 2023-01-13 00:38
@nikovacevic - Can we pick this one up?

**Comment by nikovacevic** [comment] 2023-01-13 18:22
@Sean-Holcomb is going to take some time to think about it. Sounds like this will be easier to support in Cloud Costs than in legacy Cloud Usage or Reconciliation, but we can probably support it. Will chime in again later with expected difficulty and time.

**Comment by AjayTripathy** [comment] 2023-01-30 21:17
I'm re-tagging this with 101 proposal. This feature seems to make sense to me, just needs prioritization.

**Comment by Sean-Holcomb** [comment] 2023-02-01 04:49
@siemenskyle Can you give an example of what you mean by this?
> Modifying the query to use the PARTITION function instead of _PARTITIONTIME however could allow support for views.

It sounds like you are suggesting that there is a function which returns the name of the partition column  that can be used in our queries, but I am not seeing anything like that in the documentation.

Barring that we can grab the partition column from the `.INFORMATION_SCHEMA.COLUMNS` table, if the partition is missing we can exclude that part of the WHERE clause, but if it is present we can support a view such as 
```
CREATE MATERIALIZED VIEW project.billing_data.billing-view Partition BY DATE(pt) AS
AS (
  SELECT
    *, _PARTITIONTIME as pt
  FROM
    project.billing_data.gcp_billing_export_resource_v1_ETC
  WHERE
    project.number = "1220394821"
);
```
Which will allow users to filter as needed while still receiving the cost savings of the partitioned queries. 

Also worth mentioning here, that we are limited to partitioning any view on this data on `_PARTITIONTIME` as any partition on a view must match the underlying table.

**Comment by siemenskyle** [comment] 2023-02-08 14:12
@Sean-Holcomb if I'm understanding the feedback I got from Google correctly, I think using `_PARTITIONTIME` in the Materialized View still would not work correctly. @mdebeaux may have more feedback on this though.

**Comment by Sean-Holcomb** [comment] 2023-02-08 17:45
@siemenskyle My initial test had it working. You just have to alias it when putting it in the view, as the `_PARTITIONTIME` is reserved and cannot be user defined. I am still interested to know what you meant by "use the `PARTITION` function" in the original comment. I just want to make sure I am not missing a useful tool if it exists.

**Comment by mattdbx** [comment] 2023-02-09 11:05
@Sean-Holcomb @siemenskyle Hey there, let me try to give more context on the discussion we had with Kyle :)

The end goal is to enable opencost to run on datasets that are not the raw billing export we generate on the GCP side. The idea being that teams want to use opencost on a subset of this data or a transformed/cleaned version of the raw data.

To do so it means opencost should be able to run both on:
1. **Materliazed Views** derived of the raw table or
2. **New tables** created (with the same data structure) from the raw table.

In both cases, the `_PARTITIONTIME` pseudo column will not exist.
As you said @Sean-Holcomb for MVs it needs to be renamed and for newly created tables, there is a chance that they will not be ingestion-time partitioned but time-unit column-partitioned (if the transformation is not realtime).
https://cloud.google.com/bigquery/docs/partitioned-tables#types_of_partitioning

Therefore the idea we discussed with Kyle is to have opencost flexible on the selection of the partitioning column rather than assuming that `_PARTITIONTIME` will exist.

WDYT @Sean-Holcomb ?

**Comment by Sean-Holcomb** [comment] 2023-02-13 19:05
I am unsure if there is a way to detect what kind of partition is being used, in the short term I don't think we will be able to support partition types other than insertion time, but we should be able to support no partition.

**Comment by florianmutter** [comment] 2024-11-29 08:12
Was this solved or is it still open?

**Comment by Sean-Holcomb** [comment] 2024-12-02 04:32
The issue is still open, the issue remains that `_PARTITIONTIME` psudo-column, which contains the insertion time on the standard usage export, is not present on views derived from that dataset. It would still be possible to not query for that column if it is not present.

**Comment by chipzoller** [comment] 2024-12-03 12:53
Transferred this internally to enhancement [KC-354](https://kubecost.atlassian.net/browse/KC-354).

Since this is not a Helm chart specific feature request, let's leave this closed as all features and bugs have been moved to https://support.kubecost.com.

[KC-354]: https://kubecost.atlassian.net/browse/KC-354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Closed as completed by chipzoller** 2024-12-03 12:53 UTC
Labels: enhancement
