### ISSUE TITLE
NaN in Allocations report graph an multiple other places

### ISSUE THREAD

**Issue by KevinDW-Fluxys** [kubecost/cost-analyzer-helm-chart#2350] opened 2023-06-14 07:49 UTC
**Describe the bug**  
Allocations dashboard is showing NaN, advanced report not loading, Cost Center Report throwing error. It seems that there is somewhere an NaN value that is not properly handled which reflects in different areas of the application.

**To Reproduce**  
I can not specifically reproduce it. We just did a redeploy of our entire cluster and the error is gone again (but so is the data, as we are not persisting it atm)
I had the same problem before, where it arrived after some days.
I was making some configurational changes at the time, but I can't say for sure they are related. The changes I was mainly making was: adding/removing cloud integration configuration, modifiying shared namespaces in the settings and starting to tag resources in azure with kubernetes_namespace tag.

**Expected behavior**  
There should not be NaN errors in the UI

**Screenshots**  
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/122517058/74b01260-3d6e-4baa-8f39-b87c991bc1df)
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/122517058/5210b801-76c6-4302-a5db-67e01dfc1bff)
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/122517058/dec3a0c2-4965-4d01-b2c6-8026e41bd94c)

**What impact will this have on your ability to get value out of Kubecost?**
We are currently still evaluating. We were planning to use Kubecost Enterprise, but if we can't resolve this bug we will have to find another solution.

**Bug report**
I have sent the bug report via Slack to Ross Fisher, along with other logs. Please consult him for this information, as i prefer not to publicly disclose logs etc.

**Please share the support case, if any**  
https://kubecost.slack.com/archives/CLFV60Y90/p1685619910056879

**Comment by thomasvn** [comment] 2023-06-14 20:54
@KevinDW-Fluxys Thanks for reporting, I've logged this as a bug and we're aiming to investigate & fix in the upcoming release.

Quickly looking over the HAR file, I see that you're getting HTTP 500s for Cost Center Reports (note that this is a new feature in v1.104). Now that you've redeployed Kubecost, could you provide more detail about when you are seeing `NaN` in the Allocations view? And under what configurations & circumstances? In the meantime we'll continue to investigate!

**Comment by nealormsbee** [comment] 2023-06-19 21:37
Hi folks. I'm hoping to shed a little light here.

## NaN values in the tooltip

This was a client-side issue in 1.104 where we attempted to show the top `N` costs for a day, and lump all other costs into a category called `other`. In cases where there weren't any other costs to put in the `other` category, a logic error would make produce `other: NaN` rather than leaving that category absent, which was the intended behavior. This also caused the total to show up as `NaN`, when `other` costs were summed with the top `N` costs.

This has been addressed and will be resolved in the 1.105 release.

The log indicating `detected illegal sharing coefficient: NaN (setting to zero)` is actually benign and indicates the server working as intended. An invalid value for shared costs was passed, and so it was ignored and set to 0.

## Cost Center Reports Error

More information here would be beneficial. As mentioned, Cost Center Reports are a new beta feature that we expect to encounter some issues. Any additional info you can provide on the nature of the error will help us resolve the problem you're experiencing, and make it more robust for all users in the future!

I also see that the OP has a screenshot of our longer-standing Advanced Reports failing to load. Has that been an issue as well?

Cheers.

**Comment by KevinDW-Fluxys** [comment] 2023-06-20 06:25
Hi @nealormsbee 

Thanks for the clarification on the NaN issue, It does seem what we are running into, so I will be waiting for v1.105 for this fix.

Regarding the cost center reports error: I don't think it is related, but i can give more details about whats going on (i also mentioned them on #1580 along with some other feedback about the report)
- Deleting a filter when you have multiple filters set will delete all filters
- Filters don't always seem to take effect and sometimes get removed after saving the report
- I had on multiple occasions a report which failed to load after making some changes. Removing the cost centers and adding them again would make it work again, even if it had the same parameters

The first two are easily reproduceable as they occur every time for me. The third one i haven't seen any more, but i also stopped working with the report. 

If you want some extra logs/screenshots let me know, I can send it via Slack DM.

**Comment by nealormsbee** [comment] 2023-06-25 20:02
Thanks for that @KevinDW-Fluxys!

The eng team is apprised of these issues and they're on the list of bugs we want to tackle before the v1.105.0 release. We'll give a status update here at release time.

On the other issue (#1580), I'm a fan of your suggestion to make cost centers "generatable".  I'm not sure if we'd do something like that, or just fix our existing Advanced Reports experience (which ties a K8s NS to cloud costs based on a rule, effectively accomplishing the same thing), but I can see from your explanation where Cost Center Reports fails to meet your current needs.

**Comment by nealormsbee** [comment] 2023-07-07 15:18
Status update @KevinDW-Fluxys:

>Deleting a filter when you have multiple filters set will delete all filters

This will be resolved in the 1.105 release :white_check_mark: 

>Filters don't always seem to take effect and sometimes get removed after saving the report

I have a question about this one. Does this reliably happen for filters that are still in the text field? For example:

![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/981904/3d1c843b-7433-43c2-81d6-9ec131adbcba)
vs.
![image](https://github.com/kubecost/cost-analyzer-helm-chart/assets/981904/862a2d87-88d7-4c15-93af-0053ca4392dc)

The former will consistently drop the filter (an obnoxious piece of UX that we intend to fix). I haven't been able to reproduce the issue with the latter screenshot (yet) but will continue to pursue if that's where you're seeing an issue.

>I had on multiple occasions a report which failed to load after making some changes. Removing the cost centers and adding them again would make it work again, even if it had the same parameters.

I haven't reproduced this one yet. I imagine it is more likely to occur on production systems with larger amounts of data that those I've tested against so far, likely as a result of a larger query failing. Will continue attempting to reproduce on my end, and in the meantime we can add some simple retry logic which may help.

**Comment by chipzoller** [comment] 2024-05-02 01:10
Closing, stale.

**Closed as completed by chipzoller** 2024-05-02 01:10 UTC
Labels: bug, needs-triage
