### ISSUE TITLE
Forecast doesn't support IPv6 only EKS Cluster

### ISSUE THREAD

**Issue by sdomme** [kubecost/cost-analyzer-helm-chart#3446] opened 2024-05-31 12:27 UTC
### Kubecost Helm Chart Version

2.2.5

### Kubernetes Version

1.29

### Kubernetes Platform

EKS

### Description

Hello,

the Forecast component does not support IPv6-only Cluster. It only listen on `0.0.0.0:5000`
```
[2024-05-31 11:55:31 +0000] [1] [INFO] Starting gunicorn 21.2.0
[2024-05-31 11:55:31 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
```

Configuring `"GUNICORN_CMD_ARGS":  "--log-level info -t 1200 -b [::]:5000"` as env via forecasting.env Helm key also doesn't help as per the gunicorn documentation the configuration file takes precedence:

[doc](https://docs.gunicorn.org/en/latest/configure.html)
```
When a configuration file is specified in the command line arguments and in the GUNICORN_CMD_ARGS environment variable, only the configuration file specified on the command line is used.
```

From the debug log of the starting container:

```
[2024-05-31 12:04:59 +0000] [1] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:5000']
```  
 

### Steps to reproduce

1.  Run kubecost on IPv6-only EKS cluster 

### Expected behavior

Forecast component works out of the box, since it is enabled per default.

### Impact

Can not use forecast

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment] 2024-05-31 12:33
Duplicate of https://github.com/kubecost/features-bugs/issues/73

**Closed as completed by chipzoller** 2024-05-31 12:33 UTC
