### ISSUE TITLE
Panic in cost-analyzer container

### ISSUE THREAD

**Issue by zorrobyte** [kubecost/cost-analyzer-helm-chart#1545] opened 2022-07-12 13:48 UTC
```
2022-07-12T02:49:40.049029576Z INF Panic: runtime error: invalid memory address or nil pointer dereference


runtime/debug.Stack()

	/usr/local/go/src/runtime/debug/stack.go:24 +0x65

<[http://golang.org/x/sync/singleflight.newPanicError({0x1fbcee0|golang.org/x/sync/singleflight.newPanicError({0x1fbcee0](http://golang.org/x/sync/singleflight.newPanicError(%7B0x1fbcee0|golang.org/x/sync/singleflight.newPanicError(%7B0x1fbcee0)>?, 0x372b1a0})

	/go/pkg/mod/golang.org/x/[sync@v0.0.0-20210220032951-036812b2e83c](mailto:sync@v0.0.0-20210220032951-036812b2e83c)/singleflight/singleflight.go:35 +0x2c

<http://golang.org/x/sync/singleflight.(*Group).doCall.func2.1()|golang.org/x/sync/singleflight.(*Group).doCall.func2.1()>

	/go/pkg/mod/golang.org/x/[sync@v0.0.0-20210220032951-036812b2e83c](mailto:sync@v0.0.0-20210220032951-036812b2e83c)/singleflight/singleflight.go:188 +0x3b

panic({0x1fbcee0, 0x372b1a0})

	/usr/local/go/src/runtime/panic.go:838 +0x207

net/http.HandlerFunc.ServeHTTP(0xdc87e44598?, {0x27e37b0?, 0xdc5408a540?}, 0xc001f00400?)

	/usr/local/go/src/net/http/server.go:2084 +0x2f

net/http.serverHandler.ServeHTTP({0xdc87e3f770?}, {0x27e37b0, 0xdc5408a540}, 0xdc5186cd00)

	/usr/local/go/src/net/http/server.go:2916 +0x43b

net/http.(*conn).serve(0xdc7821d680, {0x27e4a30, 0xc065167020})

	/usr/local/go/src/net/http/server.go:1966 +0x5d7

created by net/http.(*Server).Serve

	/usr/local/go/src/net/http/server.go:3071 +0x4db

	/usr/local/go/src/net/http/server.go:2084 +0x2f

net/http.(*ServeMux).ServeHTTP(0x14?, {0x27d9310, 0xdc87e3f860}, 0xdc5186cd00)

	/usr/local/go/src/net/http/server.go:2462 +0x149

<[http://github.com/kubecost/opencost/pkg/errors.PanicHandlerMiddleware.func1(|github.com/kubecost/opencost/pkg/errors.PanicHandlerMiddleware.func1(>{0x27d9310](http://github.com/kubecost/opencost/pkg/errors.PanicHandlerMiddleware.func1(|github.com/kubecost/opencost/pkg/errors.PanicHandlerMiddleware.func1(%3E%7B0x27d9310)?, 0xdc87e3f860?}, 0x4c1537?)

	/app/opencost/pkg/errors/panic.go:76 +0x8f

net/http.HandlerFunc.ServeHTTP(0xc002017901?, {0x27d9310?, 0xdc87e3f860?}, 0x0?)

	/usr/local/go/src/net/http/server.go:2084 +0x2f

<[http://github.com/kubecost/opencost/pkg/metrics.ResponseMetricMiddleware.func1(|github.com/kubecost/opencost/pkg/metrics.ResponseMetricMiddleware.func1(>{0x27e37b0](http://github.com/kubecost/opencost/pkg/metrics.ResponseMetricMiddleware.func1(|github.com/kubecost/opencost/pkg/metrics.ResponseMetricMiddleware.func1(%3E%7B0x27e37b0)?, 0xdc5408a540}, 0xdc5186cd00)

	/app/opencost/pkg/metrics/httpmetricmiddleware.go:25 +0x124

net/http.HandlerFunc.ServeHTTP(0xc064822580?, {0x27e37b0?, 0xdc5408a540?}, 0xdc5186cd00?)

	/usr/local/go/src/net/http/server.go:2084 +0x2f

<[http://github.com/rs/cors.(*Cors).Handler.func1(|github.com/rs/cors.(*Cors).Handler.func1(>{0x27e37b0](http://github.com/rs/cors.(*Cors).Handler.func1(|github.com/rs/cors.(*Cors).Handler.func1(%3E%7B0x27e37b0), 0xdc5408a540}, 0xdc5186cd00)

	/go/pkg/mod/github.com/rs/[cors@v1.7.0](mailto:cors@v1.7.0)/cors.go:219 +0x1bd

net/http.HandlerFunc.ServeHTTP(0xdc87e44598?, {0x27e37b0?, 0xdc5408a540?}, 0xc001f00400?)

	/usr/local/go/src/net/http/server.go:2084 +0x2f

net/http.serverHandler.ServeHTTP({0xdc87e3f770?}, {0x27e37b0, 0xdc5408a540}, 0xdc5186cd00)

	/usr/local/go/src/net/http/server.go:2916 +0x43b

net/http.(*conn).serve(0xdc7821d680, {0x27e4a30, 0xc065167020})

	/usr/local/go/src/net/http/server.go:1966 +0x5d7

created by net/http.(*Server).Serve

	/usr/local/go/src/net/http/server.go:3071 +0x4db
```

gz#2162<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2162'>Zendesk ticket #2162</a>)</i>

Customer will be sharing the version shortly

gz#2156<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/2156'>Zendesk ticket #2156</a>)</i>

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-124) by [Unito](https://www.unito.io)

**Comment by dwbrown2** [comment] 2022-07-12 16:51
Thanks for reporting, @zorrobyte! Can you share what version this was from?

**Comment by zorrobyte** [comment] 2022-07-12 23:42
This is on version 1.94.3 - ZD 1972

**Comment by dwbrown2** [comment] 2022-07-12 23:43
Thanks! @AjayTripathy @sundeepghuman would this be relevant in 1.95 release?

**Comment by AjayTripathy** [comment] 2022-07-13 01:48
Thanks for the report. These tickets need a bit more context like what page of the application triggers the error and whether this is ongoing or intermittent to determine priority since we're so close to the release cut date. @zorrobyte can you please collect that information and add it to the ticket, then add that to the context required to file tickets like this?

**Comment by zorrobyte** [comment] 2022-07-14 15:18
Thank you for the feedback @AjayTripathy 

The customer is reporting that it sometimes when using allocation summary API. Would their API call be helpful? I'll ask them for it and update when I get it from the customer

**Comment by Adam-Stack-PM** [comment] 2022-07-20 22:42
@AjayTripathy, Could you look into this or point me in the right direction for who could help triage?

**Comment by Adam-Stack-PM** [comment] 2022-08-15 23:28
@AjayTripathy, Could you help assign this a priority status and release target?

**Comment by AjayTripathy** [comment] 2022-08-19 05:18
Let's get this double checked during our v1.97 bug testing @Adam-Stack-PM . I _think_ this has already been fixed or gone away but not positive.

**Comment by sundeepghuman** [comment] 2022-09-07 17:00
We still don't have the exact details on their cluster to help us reproduce

**Comment by biancaburtoiu** [comment] 2022-09-08 20:58
@mbolt35 has helped me look into this and while we haven't found the root cause yet, we're looking at potential issues in the cache group, wrt single flighting the summary allocation requests. 

In absence of more details and/or similar complaints, downgrading this from P1. Will send further updates.

**Comment by mbolt35** [comment] 2022-09-08 21:37
Here is the actual stack trace (we located it in Sentry):
```
Panic: runtime error: invalid memory address or nil pointer dereference

runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
golang.org/x/sync/singleflight.newPanicError({0x1fbcee0?, 0x372b1a0})
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:35 +0x2c
golang.org/x/sync/singleflight.(*Group).doCall.func2.1()
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:188 +0x3b
panic({0x1fbcee0, 0x372b1a0})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/kubecost/kubecost-cost-model/pkg/savings.allocationSetRangeToMaxHRRecommendations(0x27c61a0?, {0x0, 0x0}, {0x27e99c0, 0xc00d27e280}, 0xc0cf0e7a80?, 0x1?)
	/app/kubecost-cost-model/pkg/savings/requestsizing.go:670 +0xa02
github.com/kubecost/kubecost-cost-model/pkg/savings.(*Optimizer).RecommendRequestSizes(0xc022d4d360, 0xc052de5520)
	/app/kubecost-cost-model/pkg/savings/requestsizing.go:1043 +0x19a
github.com/kubecost/kubecost-cost-model/pkg/savings.(*Optimizer).RequestSizingHandler.func2()
	/app/kubecost-cost-model/pkg/savings/handlers.go:178 +0x25
golang.org/x/sync/singleflight.(*Group).doCall.func2(0xc052de5366, 0xc2b509f200, 0x60?)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:193 +0x6f
golang.org/x/sync/singleflight.(*Group).doCall(0x1f90d80?, 0xc10753c270?, {0xc23ee67cb0?, 0x28?}, 0x1?)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:195 +0xa5
golang.org/x/sync/singleflight.(*Group).Do(0xc022d4d380, {0xc23ee67cb0, 0x28}, 0x1?)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:108 +0x154
github.com/kubecost/kubecost-cost-model/pkg/savings.(*Optimizer).RequestSizingHandler(0xc022d4d360, {0x27d9310, 0xc1636026f0}, 0xc0577ad000, {0xc021418a00?, 0x0?, 0xc0a0a648cd?})
	/app/kubecost-cost-model/pkg/savings/handlers.go:175 +0x5e5
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0239f8300, {0x27d9310, 0xc1636026f0}, 0xc0577ad000)
	/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0x82b
github.com/kubecost/kubecost-cost-model/pkg/product.WindowRestrictionMiddleware.func1({0x27d9310, 0xc1636026f0}, 0xc0577ad000)
	/app/kubecost-cost-model/pkg/product/productkeymiddleware.go:56 +0x44e
net/http.HandlerFunc.ServeHTTP(0x20307f?, {0x27d9310?, 0xc1636026f0?}, 0xc029ec98b8?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x14?, {0x27d9310, 0xc1636026f0}, 0xc0577ad000)
	/usr/local/go/src/net/http/server.go:2462 +0x149
github.com/kubecost/opencost/pkg/errors.PanicHandlerMiddleware.func1({0x27d9310?, 0xc1636026f0?}, 0x4c1537?)
	/app/opencost/pkg/errors/panic.go:76 +0x8f
net/http.HandlerFunc.ServeHTTP(0x1?, {0x27d9310?, 0xc1636026f0?}, 0x0?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/kubecost/opencost/pkg/metrics.ResponseMetricMiddleware.func1({0x27e37b0?, 0xc27b878a80}, 0xc0577ad000)
	/app/opencost/pkg/metrics/httpmetricmiddleware.go:25 +0x124
net/http.HandlerFunc.ServeHTTP(0xc001434790?, {0x27e37b0?, 0xc27b878a80?}, 0xc0577ad000?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/rs/cors.(*Cors).Handler.func1({0x27e37b0, 0xc27b878a80}, 0xc0577ad000)
	/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1bd
net/http.HandlerFunc.ServeHTTP(0xc0a0a648db?, {0x27e37b0?, 0xc27b878a80?}, 0xc02b1b2400?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.serverHandler.ServeHTTP({0xc163602510?}, {0x27e37b0, 0xc27b878a80}, 0xc0577ad000)
	/usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0487ba500, {0x27e4a30, 0xc029ae5bf0})
	/usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x4db

StackTrace: goroutine 21462 [running]:
github.com/kubecost/opencost/pkg/errors.dispatch({0x1f6dbc0, 0xc163603410}, 0x1)
	/app/opencost/pkg/errors/panic.go:115 +0x4f
github.com/kubecost/opencost/pkg/errors.HandleHTTPPanic({0x27d9310, 0xc1636026f0}, 0x0?)
	/app/opencost/pkg/errors/panic.go:108 +0x78
panic({0x1f6dbc0, 0xc163603410})
	/usr/local/go/src/runtime/panic.go:838 +0x207
golang.org/x/sync/singleflight.(*Group).doCall.func1()
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:165 +0x2a5
golang.org/x/sync/singleflight.(*Group).doCall(0x1f90d80?, 0xc10753c270?, {0xc23ee67cb0?, 0x28?}, 0x1?)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:200 +0xc2
golang.org/x/sync/singleflight.(*Group).Do(0xc022d4d380, {0xc23ee67cb0, 0x28}, 0x1?)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/singleflight/singleflight.go:108 +0x154
github.com/kubecost/kubecost-cost-model/pkg/savings.(*Optimizer).RequestSizingHandler(0xc022d4d360, {0x27d9310, 0xc1636026f0}, 0xc0577ad000, {0xc021418a00?, 0x0?, 0xc0a0a648cd?})
	/app/kubecost-cost-model/pkg/savings/handlers.go:175 +0x5e5
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0239f8300, {0x27d9310, 0xc1636026f0}, 0xc0577ad000)
	/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0x82b
github.com/kubecost/kubecost-cost-model/pkg/product.WindowRestrictionMiddleware.func1({0x27d9310, 0xc1636026f0}, 0xc0577ad000)
	/app/kubecost-cost-model/pkg/product/productkeymiddleware.go:56 +0x44e
net/http.HandlerFunc.ServeHTTP(0x20307f?, {0x27d9310?, 0xc1636026f0?}, 0xc029ec98b8?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.(*ServeMux).ServeHTTP(0x14?, {0x27d9310, 0xc1636026f0}, 0xc0577ad000)
	/usr/local/go/src/net/http/server.go:2462 +0x149
github.com/kubecost/opencost/pkg/errors.PanicHandlerMiddleware.func1({0x27d9310?, 0xc1636026f0?}, 0x4c1537?)
	/app/opencost/pkg/errors/panic.go:76 +0x8f
net/http.HandlerFunc.ServeHTTP(0x1?, {0x27d9310?, 0xc1636026f0?}, 0x0?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/kubecost/opencost/pkg/metrics.ResponseMetricMiddleware.func1({0x27e37b0?, 0xc27b878a80}, 0xc0577ad000)
	/app/opencost/pkg/metrics/httpmetricmiddleware.go:25 +0x124
net/http.HandlerFunc.ServeHTTP(0xc001434790?, {0x27e37b0?, 0xc27b878a80?}, 0xc0577ad000?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
github.com/rs/cors.(*Cors).Handler.func1({0x27e37b0, 0xc27b878a80}, 0xc0577ad000)
	/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1bd
net/http.HandlerFunc.ServeHTTP(0xc0a0a648db?, {0x27e37b0?, 0xc27b878a80?}, 0xc02b1b2400?)
	/usr/local/go/src/net/http/server.go:2084 +0x2f
net/http.serverHandler.ServeHTTP({0xc163602510?}, {0x27e37b0, 0xc27b878a80}, 0xc0577ad000)
	/usr/local/go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc0487ba500, {0x27e4a30, 0xc029ae5bf0})
	/usr/local/go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x4db
```

**Comment by biancaburtoiu** [comment] 2022-09-09 16:36
Given this new stack trace the issue seems to be in the single flighting used in optimisations - in this case specifically in request sizing. The problematic code segment processes an accumulated allocationSet whose `Window` seems to be null. 

I see @michaelmdresser did some [work](https://github.com/kubecost/kubecost-cost-model/pull/746) here a couple of months ago, he might be able to share more context here?

**Comment by michaelmdresser** [comment] 2022-09-12 18:25
Here's the line of code `/app/kubecost-cost-model/pkg/savings/requestsizing.go:670` in 1.94.3 https://github.com/kubecost/kubecost-cost-model/blob/4ebe7c88b4492d492e5431d2449c18af9646eeb5/pkg/savings/requestsizing.go#L670

I think it's also possible that the AllocationSet, not it's Window, is nil because `.Each()` I think handled `nil` gracefully -- AFAICT the other uses of `as` above that line are just through `.Each()`.

Not sure what else I can offer here, let me know.

**Comment by Adam-Stack-PM** [comment] 2022-10-22 20:37
@zorrobyte, If you hear of more customers experiencing this issue, please let us know.

**Comment by BouchaaraAdil** [comment] 2023-04-06 10:36
i have the same issue, once i upgraded to upgrade kubecost chart to 1.102.0

**Comment by teevans** [comment] 2023-04-06 18:15
Hey @BouchaaraAdil - we shipped a patch this morning V1.102.1 that should correct this panic issue, let me know if that doesn't fix the issue!

**Comment by ftaib** [comment] 2023-04-11 16:54
Hi, I have the same issue for v1.102.1

```log
2023-04-11T16:50:27.080330718Z INF Asset[1d]: AggregatedStore.Run[tDPoC]: run: aggregated [2023-04-11T00:00:00+0000, 2023-04-12T00:00:00+0000) from 4 to 4 in 297.375µs
2023-04-11T16:50:36.088344737Z INF Panic: runtime error: invalid memory address or nil pointer dereference
StackTrace: goroutine 180688 [running]:
github.com/opencost/opencost/pkg/errors.dispatch({0x324b0c0, 0x62befe0}, 0x1)
	/app/opencost/pkg/errors/panic.go:115 +0x4f
github.com/opencost/opencost/pkg/errors.HandleHTTPPanic({0x45abe10, 0xc007682de0}, 0xc001235110?)
	/app/opencost/pkg/errors/panic.go:108 +0x78
panic({0x324b0c0, 0x62befe0})
	/usr/local/go/src/runtime/panic.go:884 +0x213
github.com/opencost/opencost/pkg/cloud.(*AWS).findCostForDisk(0xc0020d9a00, 0xc00587d980)
	/app/opencost/pkg/cloud/awsprovider.go:1773 +0x9c
github.com/opencost/opencost/pkg/cloud.(*AWS).GetOrphanedResources(0x34f5380?)
	/app/opencost/pkg/cloud/awsprovider.go:1694 +0x136
github.com/kubecost/kubecost-cost-model/pkg/cmd/costmodel.(*Accesses).OrphanedResourcesHandler(0xc002107b80, {0x45abe10, 0xc007682de0}, 0x75668d?, {0xc002823b80?, 0x0?, 0xc00666045d?})
	/app/kubecost-cost-model/pkg/cmd/costmodel/costmodel.go:1231 +0xd5
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0024bed20, {0x45abe10, 0xc007682de0}, 0xc00576fd00)
	/go/pkg/mod/github.com/julienschmidt/httprouter@v1.3.0/router.go:387 +0x81c
github.com/kubecost/kubecost-cost-model/pkg/product.WindowRestrictionMiddleware.func1({0x45abe10, 0xc007682de0}, 0xc00576fd00)
	/app/kubecost-cost-model/pkg/product/productkeymiddleware.go:26 +0x576
net/http.HandlerFunc.ServeHTTP(0x41b5f1?, {0x45abe10?, 0xc007682de0?}, 0x414ca5?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
net/http.(*ServeMux).ServeHTTP(0x30?, {0x45abe10, 0xc007682de0}, 0xc00576fd00)
	/usr/local/go/src/net/http/server.go:2500 +0x149
github.com/opencost/opencost/pkg/errors.PanicHandlerMiddleware.func1({0x45abe10?, 0xc007682de0?}, 0x493bd7?)
	/app/opencost/pkg/errors/panic.go:76 +0x8f
net/http.HandlerFunc.ServeHTTP(0x30a01e0?, {0x45abe10?, 0xc007682de0?}, 0x1?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/opencost/opencost/pkg/metrics.ResponseMetricMiddleware.func1({0x45b8500?, 0xc0036c1b20}, 0xc00576fd00)
	/app/opencost/pkg/metrics/httpmetricmiddleware.go:25 +0x124
net/http.HandlerFunc.ServeHTTP(0xc002802240?, {0x45b8500?, 0xc0036c1b20?}, 0xc00576fd00?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/rs/cors.(*Cors).Handler.func1({0x45b8500, 0xc0036c1b20}, 0xc00576fd00)
	/go/pkg/mod/github.com/rs/cors@v1.8.2/cors.go:231 +0x1c4
net/http.HandlerFunc.ServeHTTP(0xc007682d50?, {0x45b8500?, 0xc0036c1b20?}, 0xc001fc8e18?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
github.com/kubecost/kubecost-cost-model/pkg/profilemiddleware.(*HTTPProfilingManager).CPUProfileMiddleware.func1({0x45b8500?, 0xc0036c1b20?}, 0xc00576fd00?)
	/app/kubecost-cost-model/pkg/profilemiddleware/profilemiddleware.go:46 +0x6c7
net/http.HandlerFunc.ServeHTTP(0x0?, {0x45b8500?, 0xc0036c1b20?}, 0x46dc8e?)
	/usr/local/go/src/net/http/server.go:2122 +0x2f
net/http.serverHandler.ServeHTTP({0xc007682d20?}, {0x45b8500, 0xc0036c1b20}, 0xc00576fd00)
	/usr/local/go/src/net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc001fc8cf0, {0x45ba540, 0xc002832540})
	/usr/local/go/src/net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3089 +0x5ed
```

**Comment by teevans** [comment] 2023-04-11 16:56
Hey folks, it looks like this issue is now getting used for several unrelated panic issues. Going to close this one. 

@ftaib - Can I bother you to open a new issue for your panic?

**Closed by teevans** 2023-04-11 16:56 UTC
Labels: bug, P2, api
