### ISSUE TITLE
[Bug] Label mapping configs do not work out of the box

### ISSUE THREAD

**Issue by dgaffuri** [kubecost/cost-analyzer-helm-chart#3264] opened 2024-03-22 16:13 UTC
### Kubecost Helm Chart Version

2.1.1

### Kubernetes Version

1.29.1

### Kubernetes Platform

EKS

### Description

Defining and enabling kubecostProductConfigs.labelMappingConfigs creates the config map named by default "app-configs", but the config map is mounted and passed as APP_CONFIGMAP_NAME environment variable to cost-model only if the undocumented appConfigmapName value is defined too

### Steps to reproduce

1. set kubecostProductConfigs.labelMappingConfigs to `cluster_external_label: "cluster-name"`
2. set kubecostProductConfigs.labelMappingConfigs.enabled to `true`
3. deploy the chart
4. open Monitor, Cloud Costs Explorer in the frontend

### Expected behavior

external costs of resources tagged with "cluster-name: prod" would be allocated to the "prod" cluster

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by jessegoodier** [comment] 2024-03-27 16:36
Looks like a bug to me, thanks for the detail here!
Will get this fixed in our 2.2 or 2.2.1 release.

**Comment by Hronom** [comment] 2024-03-31 16:01
stops working in 2.2.0

**Comment by Hronom** [comment] 2024-03-31 16:31
I try to set `appConfigmapName: app-configs` and it not helps. @dgaffuri what else you did to fix this?

**Comment by dgaffuri** [comment] 2024-04-03 16:09
@Hronom I only notice that defining the value the config map name was passed to deployment as an environment variable, I've not yet checked if the mappings work

**Comment by AjayTripathy** [comment] 2024-04-04 01:18
@jessegoodier were we able to reproduce this?

**Comment by jessegoodier** [comment] 2024-04-17 20:17
I was mistaken- label mapping never was intended to change the cloud cost display. 

In Kubecost 1.x, there was a tool called advanced reports. This is where those mappings were used.

In 2.x, `Advanced reports` has been replaced with collections, which has a much simpler interface and the ability to find labels easily with autocomplete.
https://blog.kubecost.com/blog/introducing-kubecost-collections/

Can you take a look at this and let us know if this works?

**Comment by Hronom** [comment] 2024-04-17 23:54
Seems like it was general issue after upgrade from `2.1.0` to `2.2.0`. I wipe all data and switched to usage of `cloudIntegrationJSON` and everything is ok now

**Comment by jessegoodier** [comment] 2024-04-18 00:46
> Seems like it was general issue after upgrade from `2.1.0` to `2.2.0`. I wipe all data and switched to usage of `cloudIntegrationJSON` and everything is ok now

Oh, I'm very interested in your findings on that.

It sounds like the helm values in kubecostProductConfigs for cloud integration broke and only started to work when you configured `cloudIntegrationJSON`?
FWIW, I tested that today and both worked, so there is some combination of settings which are conflicting.

Please let me know if you have ideas on that. Can you share your previous settings that didn't work?

**Closed as completed** 2024-05-03 13:21 UTC
Labels: bug, needs-triage

**Comment by pandvan** [comment] 2024-07-05 12:17
We're facing a similar issue: cannot get external labels to work.
Tags has been set on AWS side and exported on the CUR but costs are never associated with the cluster monitored by kubecost. In Cloud Cost pane we see that 100% of k8s utilization is on AWS EKS, even if we tag RDS, EFS, EC2 and other resources. Is there any way to debug such issue? How to understand where/how kubecost try to read this tags and tied them with k8s resources?

**Comment by jessegoodier** [comment] 2024-07-19 22:19
@pandvan could you share your helm values and what version you are using?

**Comment by pandvan** [comment] 2024-07-20 06:26
We're using version 2.3.2
Here below Helm chart values
```yaml
cost-analyzer:
  kubecostFrontend:
    image: public.ecr.aws/kubecost/frontend
  kubecostModel:
    image: public.ecr.aws/kubecost/cost-model
  forecasting:
    fullImageName: public.ecr.aws/kubecost/kubecost-modeling:v0.1.12
  networkCosts:
    image:
      repository: public.ecr.aws/kubecost/kubecost-network-costs
  clusterController:
    image:
      repository: public.ecr.aws/kubecost/cluster-controller
  prometheus:
    server:
      image:
        repository: public.ecr.aws/kubecost/prometheus
    configmapReload:
      prometheus:
        image:
          repository: public.ecr.aws/kubecost/prometheus-config-reloader
  reporting:
    productAnalytics: false
  diagnostics:
    enabled: false

  appConfigmapName: app-configs

  kubecostProductConfigs:
    # Cloud integration
    projectID: "<REDACTED>"
    createServiceKeySecret: true
    awsServiceKeyName: <REDACTED>
    awsServiceKeyPassword: <REDACTED>
    # Cost and Usage Reports (now Data Exports)
    athenaProjectID: "<REDACTED>"
    athenaBucketName: s3://<REDACTED>
    athenaRegion: eu-central-1
    athenaDatabase: athenacurcfn_kubecost
    athenaTable: kubecost
    athenaWorkgroup: primary
    # Spot instances feed
    awsSpotDataRegion: eu-central-1
    awsSpotDataBucket: <REDACTED>
    awsSpotDataPrefix: feed
    spotLabel: eks.amazonaws.com/capacityType
    spotLabelValue: SPOT
    # AWS tag - Kubecost asset mapping
    labelMappingConfigs:
      enabled: true
      namespace_external_label: "kubecost/kubernetes_namespace"
      cluster_external_label: "kubecost/kubernetes_cluster"
      controller_external_label: "kubecost/kubernetes_controller"
      product_external_label: "kubecost/kubernetes_label_app"
      service_external_label: "kubecost/kubernetes_service"
      deployment_external_label: "kubecost/kubernetes_deployment"
      team_external_label: "kubecost/kubernetes_label_team"
      environment_external_label: "kubecost/kubernetes_label_env"
      department_external_label: "kubecost/kubernetes_label_department"
      statefulset_external_label: "kubecost/kubernetes_statefulset"
      daemonset_external_label: "kubecost/kubernetes_daemonset"
      pod_external_label: "kubecost/kubernetes_pod"
    cloudAccountMapping:
      "<REDACTED>": kubernetes-prod
```

Then we tag some external AWS resources such as RDS, EC2, Elasticache ecc... with `kubecost/kubernetes_cluster: <our_cluster_name_as_seen_by_kubecost>` but we cannot understand how to see if their costs (they are present on cloud costs) have been associated with the kubernetes cluster (or other components like namespace).

**Comment by jessegoodier** [comment] 2024-07-21 14:01
The issue is likely due to the / in the label. 
It may work if you replace the / 
`pod_external_label: "kubecost/kubernetes_pod"`
`pod_external_label: "kubecost_kubernetes_pod"`
If that does not work, I believe we'd need a product change to support that use case. 
Please let us know what you find.

**Comment by pandvan** [comment] 2024-07-26 09:33
Thank you @jessegoodier for the reply. I've tried your proposal but seems that it still doesn't work, or I'm missing something.

k8s cluster is properly set, using `prometheus.server.global.external_labels.cluster_id` and `kubecostProductConfigs.clusterName` helm chart values (are both needed?)
![image](https://github.com/user-attachments/assets/655a3adb-c773-4ffe-ab77-8e328a1a504f)

In the Monitor -> Cloud Costs I can see one of RDS instances properly tagged and recognized by Kubecost.

![image](https://github.com/user-attachments/assets/ffffb7ed-98c4-467b-9db6-9e0a646d3eed)

How and where can I see that those 20 bucks are added to the entire cluster cost?

**Comment by jessegoodier** [comment] 2024-07-29 12:43
This is part of the collections functionality now. 
https://docs.kubecost.com/using-kubecost/navigating-the-kubecost-ui/collections
Which has been greatly simplified joining cloud costs to Kubernetes costs. 
The cloud tags should auto complete for you if using Kubecost 2.0+

**Comment by Jeinhaus** [comment] 2024-11-08 08:51
> This is part of the collections functionality now. https://docs.kubecost.com/using-kubecost/navigating-the-kubecost-ui/collections Which has been greatly simplified joining cloud costs to Kubernetes costs. The cloud tags should auto complete for you if using Kubecost 2.0+

How does this work with shared costs that get allocated proportionally to namespaces. This is not possible in Collections afaik. 
I would expect the out-of-cluster costs that are added to the total cluster cost via the external labels to be shared among the tenants of the cluster.
Is there any solution to this at the moment @jessegoodier ?

**Comment by jessegoodier** [comment] 2024-11-19 15:13
Sorry for the late update- we are looking at shared costs in collections in Q1

**Comment by Jeinhaus** [comment] 2024-11-20 04:42
> Sorry for the late update- we are looking at shared costs in collections in Q1

Ah, thats great to hear. Thank you for the update.
Wouldn't the external_label functionality still be required for correct shared cost computation?

**Comment by jessegoodier** [comment] 2024-11-20 21:23
@kwombach12 may have ideas on product design.

**Comment by kwombach12** [comment] 2024-11-20 21:25
We will likely have a different design which will not require the 'external_label' functionality. That functionality has been deprecated. We need to update the docs
