### ISSUE TITLE
"Cannot convert undefined or null to object" error on the assets page

### ISSUE THREAD

**Issue by jcharcalla** [kubecost/cost-analyzer-helm-chart#1507] opened 2022-06-29 19:24 UTC
**Describe the bug**
When drilling into some items on the `assets.html` page you get a `Failed to load asset data | Cannot convert undefined or null to object` error. 
<img width="359" alt="Screen Shot 2022-06-29 at 3 23 54 PM" src="https://user-images.githubusercontent.com/17748044/176519196-4727ce58-c1d7-4a7f-ade9-5ab2cdb4e2d0.png">
Changing the date window to `48hr` or `2d` displays the page properly, however selecting a short range in the past fails as well.

This issue was 1st seen by a customer attempting to aggregate by label. I was able to reproduce that scenario in my Kubecost `1.94.3` running in AWS however I have not been able to reproduce it elsewhere. Additionally the customer was also able to reproduce it when aggregating by service and attempting to drill into the `Kubernetes` line item.

**To Reproduce**
1. Drill into the `job=kubecost` line on my test cluster: http://a562c7882524f4401975c8d3f62e8b9e-136515386.us-east-1.elb.amazonaws.com/assets.html?agg=label%3Ajob
2. After drilling in and the error is displayed, Set the date window to `48hr` or `2d` to display the page correctly.
3. Repeat by drilling into the `Kubernetes` service: http://a562c7882524f4401975c8d3f62e8b9e-136515386.us-east-1.elb.amazonaws.com/assets.html?agg=service
4. Or the `Network` category: http://a562c7882524f4401975c8d3f62e8b9e-136515386.us-east-1.elb.amazonaws.com/assets.html?agg=category
5. Additionally aggregating by type fails without the need to drill in: http://a562c7882524f4401975c8d3f62e8b9e-136515386.us-east-1.elb.amazonaws.com/assets.html?agg=type

**Expected behavior**
Page displays correctly.

**Screenshots**
Aggregate by label `job`:
<img width="1402" alt="Screen Shot 2022-06-29 at 2 52 46 PM" src="https://user-images.githubusercontent.com/17748044/176518654-27fde282-e14b-4b7c-afc1-cf0ffe02c357.png">

Drill into the`job=kubecost` line item to see the error:
<img width="1401" alt="Screen Shot 2022-06-29 at 2 52 59 PM" src="https://user-images.githubusercontent.com/17748044/176518752-ce4559ee-2399-4e7a-b937-bb8bdd187528.png">

On the same error page, set the date range to `Last 48hr` for it to display properly:
<img width="1403" alt="Screen Shot 2022-06-29 at 2 53 55 PM" src="https://user-images.githubusercontent.com/17748044/176518916-99548dfb-f738-45d2-a762-d71f4d420fee.png">

**Comment by jcharcalla** [comment] 2022-06-29 19:26
@teevans Can you take a look at this one?

**Comment by teevans** [comment] 2022-06-29 20:37
Looking into it!

**Comment by jcharcalla** [comment] 2022-06-29 21:56
Attached is a HAR file showing data returned from the API during the error.
[a562c7882524f4401975c8d3f62e8b9e-136515386.us-east-1.elb.amazona.har.zip](https://github.com/kubecost/cost-analyzer-helm-chart/files/9014796/a562c7882524f4401975c8d3f62e8b9e-136515386.us-east-1.elb.amazona.har.zip)

**Comment by AjayTripathy** [comment] 2022-06-29 23:01
I would call this release blocking, let's make sure we prioritize accordingly.

**Comment by nealormsbee** [comment] 2022-06-30 05:30
Will double check in the morning, but am fairly confident this is now fixed in SPA.

There are a series of functions for getting the details of different types of assets: nodes, disks, etc.
Assets without a purpose-built function to derive details fall back to `getAnyDetail(asset)`.

This function was assuming that the asset's `labels` property would be a map, but in some cases (notably network assets), the `label` property is `null`. Iterating over it caused the error.

Solution was to check for the `labels` property of a given asset being `null`, and if so, treat it as `{}` instead.

**Comment by Adam-Stack-PM** [comment] 2022-07-05 21:17
@nealormsbee Can you confirm this is fixed? If so please close out with a note.

**Comment by nealormsbee** [comment] 2022-07-05 21:19
This is fixed in 1.95.0-rc.0 for all cases stated in the OP :+1:

The root cause was the same for all instances: not accounting for an asset having property `labels: null`, as noted in a prior comment.

**Closed by nealormsbee** 2022-07-05 21:19 UTC
Labels: v1.95, P0
