### ISSUE TITLE
Support encryption of claims when using SAML auth

### ISSUE THREAD

**Issue by kaelanspatel** [kubecost/cost-analyzer-helm-chart#1986] opened 2023-02-16 00:28 UTC
**What problem are you trying to solve?**
Certain SSO configurations (e.g. options in [Keycloak](https://www.keycloak.org/docs/10.0/securing_apps/#configuration-options) and [Okta](https://help.okta.com/en-us/Content/Topics/Security/idp-inbound-saml-reference.htm)) allow the user to encrypt the SAML assertions present in the response.

Kubecost's SSO integration does not support this, as it assumes the claims will be in plain XML for it to parse.

**Describe the solution you'd like**
A configurable decryption key that could be used to decrypt a response, and the respective backend changes to support this.

**Describe alternatives you've considered**
N/A

**How would users interact with this feature?**
Users would be able to set a helm chart parameter or secret to a key, which would let Kubecost process encrypted SAML assertions.

┆Issue is synchronized with this [Jira Task](https://kubecost.atlassian.net/browse/GIB-268) by [Unito](https://www.unito.io)

**Comment by AjayTripathy** [comment] 2023-02-23 23:01
@Adam-Stack-PM @teevans this is a customer request so I'd like to make sure this gets delivered in 102.

**Comment by ErnestG4** [comment] 2023-02-28 16:08
The customer would like to be a part of any RC or point release that's available with this feature.

**Comment by teevans** [comment] 2023-02-28 17:44
CC @kwombach12

**Comment by thomasvn** [comment] 2023-04-18 16:53
@kaelanspatel Can this issue be closed because of PR https://github.com/kubecost/cost-analyzer-helm-chart/pull/2118

**Comment by Adam-Stack-PM** [comment] 2023-04-27 17:35
Confirmed this is fixed with @kaelanspatel.

**Closed as completed by Adam-Stack-PM** 2023-04-27 17:35 UTC
Labels: enhancement, v1.103
