### ISSUE TITLE
Assets by hour beyond 2 days in the past

### ISSUE THREAD

**Issue by fgiannetti** [kubecost/cost-analyzer-helm-chart#1876] opened 2022-12-14 21:14 UTC
Hello!
We are using Kubecosts and consuming the allocation API.
We are using a date range in the 'window' parameter like this (the current date is 2022-12-14):

`/model/allocation?window=2022-12-14T00:00:00Z,2022-12-15T00:00:00Z`

The response is detailed hour by hour between 2022-12-14T00:00:00Z and the current time.

```{
  "code": 200,
    "data": [
        {
            ....
            "window": {
                    "start": "2022-12-14T00:00:00Z",
                    "end": "2022-12-14T01:00:00Z"
                },
               ....
        },
        {
            ....
            "window": {
                    "start": "2022-12-14T01:00:00Z",
                    "end": "2022-12-14T02:00:00Z"
                },
               ....
        }
       ....
```
That is OK! and works like a charm!

But, if we use a date range older than 2 days ago. For example:

`/model/allocation?window=2022-12-12T00:00:00Z,2022-12-13T00:00:00Z`

The response is grouped by the entire day

```{
  "code": 200,
    "data": [
        {
            ....
            "window": {
                    "start": "2022-12-12T00:00:00Z",
                    "end": "2022-12-13T00:00:00Z"
                },
               ....
        },
        {
            ....
            "window": {
                    "start": "2022-12-13T00:00:00Z",
                    "end": "2022-12-14T00:00:00Z"
                },
               ....
        }
       ....
```
Is this expected? the maximum horizon to get hourly windows is 2 days ago?
Or we are missing some config / query param to allow search allocations by hour but beyond 2 days ago?

Thanks to all in advance!
And Thank you all for this great tool!

**Comment by teevans** [comment] 2022-12-16 22:34
@nikovacevic - Could I bother you to explain this behavior? This is working as intended, but Niko should be able to give you better details on why it works that way!

**Comment by nikovacevic** [comment] 2022-12-16 22:59
Gladly. Our data pipeline is designed to be higher resolution (i.e. 1h) in the recent past, and lower resolution (i.e. 1d) for long time windows or longer-ago time windows. This assures faster querying for longer windows (because there is 24x less data to crunch with 1d resolution compared to 1h) while providing finer-grained analysis for "today" and "yesterday" -- as well as the ability to always serve "last 24h" as a request.

So the default settings retain hourly data for 48h and daily data for 90d. These values are configurable in the helm chart, though users should be aware that there are performance implications to radically extending either of those figures.

Thanks for your question, and let us know if we can share anything else.

**Comment by teevans** [comment] 2022-12-19 06:53
@fgiannetti - Specifically if you'd like to modify these values, feel free to extend how long we keep the hourly and daily data by modifying [these](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L338) lines in the Helm Chart! 

I'm going to close this for now, but if you have anything else we can help you with, please feel free to let us kno!

**Closed as completed by teevans** 2022-12-19 06:53 UTC

**Comment by fgiannetti** [comment] 2022-12-22 23:48
@teevans @nikovacevic Thank you so much you guys!!
Thanks for the cristal explanation!
I will take a look for those values in helm chart as you said.
Thanks again and sorry for the delay of the response! 🍻
