### ISSUE TITLE
Azure cloud integration config ignores kubecostProductConfigs

### ISSUE THREAD

**Issue by doonto** [kubecost/cost-analyzer-helm-chart#1430] opened 2022-05-19 09:52 UTC
**Describe the bug**
Azure cloud integration config ignores the helm values under kubecostProductConfigs.
Discussion and details are also available in https://kubecost.slack.com/archives/CLFV60Y90/p1652801061615549

**To Reproduce**
Install kubecost 1.90 (to see the azure config in the frontend) or 1.93.1 (latest at the moment), follow https://guide.kubecost.com/hc/en-us/articles/4407595934871-Azure-Config. I tried on both versions.

```
#setup your variables in the azure libraries before, use exact names, as in the helm step
variables:
  - group: azure-kubecost

####
                    - task: HelmDeploy@0
                      displayName: Helm upgrade install
                      inputs:
                        connectionType: Azure Resource Manager
                        azureSubscriptionEndpoint: platform-${{ variables.spokeName }}-kubernetes
                        azureResourceGroup: platform-${{ variables.spokeName }}-aks-rg
                        kubernetesCluster: mcs-${{ variables.spokeName }}-aks
                        namespace: ${{ variables.kubernetesNamespace }}
                        command: upgrade
                        useClusterAdmin: true
                        waitForExecution: false
                        chartName: ${{ variables.chartDir }}
                        releaseName: kubecost
                        arguments: -i --create-namespace -f ${{ variables.valuesDir }}/values.yaml -f ${{ variables.valuesDir }}/${{ variables.spokeName }}-values.yaml --set azureStorageAccessKey=$(azureStorageAccessKey) --set kubecostProductConfigs.azureSubscriptionID=22222222-2222-2222-2222-2222222222 --set kubecostProductConfigs.azureClientID=11111111-1111-1111-1111-111111111111 --set kubecostProductConfigs.azureTenantID=00000000-0000-0000-0000-000000000000  --set kubecostProductConfigs.azureClientPassword=$(azServiceKeyPassword) --set kubecostProductConfigs.createServiceKeySecret=true

```

**Expected behavior**
Kubecost reads the helm values and configures Azure integration attributes. In reality is ignores the azure integration attributes fron the helm values.yaml

**Screenshots**
![image](https://user-images.githubusercontent.com/32912561/169264669-729eb9e9-9482-4fab-99a7-01dcf47ffeaf.png)
![image](https://user-images.githubusercontent.com/32912561/169264712-77bfcfa4-7c24-4c7b-bb72-696f03274cca.png)

**Collect logs (please complete the following information):**

 - Run `helm ls` and paste the output here:
```
 helm ls -n kubecost
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubecost        kubecost        18              2022-05-19 09:25:40.148755546 +0000 UTC deployed        kubecost-1.0.0
```

 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-server` and paste the output here:
2022/05/19 09:27:04 Thanos is disabled for the API endpoints.
2022/05/19 09:27:04 Server is ready.
(For the 1.9.0 version)
 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-model` and paste the output here:
 - Run `kubectl logs <kubecost-cost-analyzer pod name> -n kubecost -c cost-analyzer-frontend` and paste the output here:

[kubecost-cost-analyzer-7cb8b6dd7c-wm2f6.log](https://github.com/kubecost/cost-analyzer-helm-chart/files/8727994/kubecost-cost-analyzer-7cb8b6dd7c-wm2f6.log)
[kubecost-cost-analyzer-frontend-7cb8b6dd7c-wm2f6.log](https://github.com/kubecost/cost-analyzer-helm-chart/files/8727997/kubecost-cost-analyzer-frontend-7cb8b6dd7c-wm2f6.log)

The bug report:
[kubecost-bug-report-1652884064842.txt](https://github.com/kubecost/cost-analyzer-helm-chart/files/8728010/kubecost-bug-report-1652884064842.txt)

gz#1845<br><br><i>(related to <a href='https://kubecost.zendesk.com/agent/tickets/1845'>Zendesk ticket #1845</a>)</i>

**Comment by AjayTripathy** [comment] 2022-06-07 06:40
Hi @doonto can you try setting the variable kubecostProductConfigs.createServiceKeySecret to true as well? I was able to get this to work by setting that.
https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/values.yaml#L783

**Comment by torbjoernk** [comment] 2022-08-31 10:08
Issue still persists and I'm facing it as well. Using v1.96.0.

@AjayTripathy, `kubecostProductConfigs.createServiceKeySecret=true` does not have the promised effect.

However, the variable `azureStorageCreateSecret` checked for in https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/azure-storage-config-secret.yaml#L3 isn't present in the values.yaml.

Defining all of the variables in value.yaml that are checked fro in the template above (`azure-storage-config-secret.yaml`) does at least result in the corresponding Secret being deployed to k8s.

I could verify, that the secret is correctly mounted into the `cost-model` Pod of the `kubecost-cost-analyzer` Deployment. However, I have the feeling, that the values from `/var/azure-storage-config` are not read in at any time.

---

Side note (likely other issue/bug): Having the Secret not configured/deployed and trying to set the variables from within the WebUI seems to not work - at least within my cluster. After hitting "Save" in the settings, the "wheel of death" does not stop spinning. After several minutes, I've deleted the whole Helm chart and started again from scratch.

---

However, I'm curious about this deprecation warning in the inline comment in `azure-storage-config-secret.yaml`. **What is the preferred option?** Using a service credential configured via AD (as promised by `azure-service-key-secret.yaml`) is not an option for me as I do not have the possibility to mock around with our AD.

**Comment by nikovacevic** [comment] 2022-09-13 21:05
Hi @torbjoernk and @doonto -- we are looking into this issue and will get back to you as soon as we can! Thank you for your patience.

**Comment by doonto** [comment] 2022-09-16 12:47
I just wanted to say, that I've posted couple of month ago the workaround in the Slack here: https://app.slack.com/client/TE6RTBNET/search/search-eyJkIjoiYXp1cmVDbGllbnRJRCIsImsiOiJ0aW1lc3RhbXAiLCJxIjoiVTAzMDdORDZRTlEiLCJyIjoiYXp1cmVDbGllbnRJRCJ9/thread/CLFV60Y90-1652801061.615549

We are still hoping, that the price data we receive by the costexport is enough, and the RateCard integration is not needed, when the cost export is there. And that you'll fix the RateCard failing items in diagnostics

**Comment by Adam-Stack-PM** [comment] 2022-09-23 23:59
@doonto, This issue is still on my radar and will follow up next week.

**Comment by doonto** [comment] 2022-09-28 07:11
I'll add here some comments from the slack channel:

Since you are using the kubecostProductConfigs.cloudIntegrationSecret value and cloud-integration.json secret the following kubecostProductConfigs values should not be needed.
```
    azureStorageContainer: kubecost
    azureContainerPath: kubecost
    azureStorageAccessKey: azureStorageAccessKey
```
The error Configure Azure Storage Failed azure storage config not found is a false positive as well, due to azureStorageSecretName not being set. I works because you are using the cloud-integration.json.

**Comment by jcharcalla** [comment] 2022-09-28 14:58
To clarify the recommendation above on using the `cloud-integration.json` secret as [documented here](https://guide.kubecost.com/hc/en-us/articles/4407595968919) is for the Cloud Integration only, it does not configure the Rate card integration. As [noted here](https://guide.kubecost.com/hc/en-us/articles/4407595934871-Azure-Config#azure-rate-card-configuration) the Cloud Integration provides similar functionality plus external costs.

We will work on reproducing the issue of kubecostProductConfigs not updating the Azure config.

**Comment by thomasvn** [comment] 2022-09-28 20:29
We were able to reproduce the reported issue. As shown below, using the `.Values.kubecostProductConfig.azureStorageSecretName` will not result in the cloud integration properly being set up. This was tested on both an existing install, and a fresh install of Kubecost of 1.96.0.

However, using `.Values.kubecostProductConfigs.cloudIntegrationSecret` will be successful. Documented [here](https://guide.kubecost.com/hc/en-us/articles/4407595968919-Setting-Up-Cloud-Integrations). This is likely because the `cloudIntegrationSecret` is the newer and more streamlined method of setting up cloud integrations.

```
$ cat azure-storage-config.json
{
  “azureSubscriptionID”: “<SUBSCRIPTION_ID>”,
  “azureStorageAccount”: “<STORAGE_ACCOUNT_NAME>”,
  “azureStorageAccessKey”: “<STORE_ACCESS_KEY>”,
  “azureStorageContainer”: “<REPORT_CONTAINER_NAME>”,
  “azureContainerPath”: “<AZURE_CONTAINER_PATH>”,
  “azureCloud”: “<AZURE_CLOUD>”
}

$ kubectl create secret generic myAzureConfig --from-file=azure-storage-config.json -n kubecost

$ helm upgrade kubecost kubecost/cost-analyzer \
  --namespace kubecost \
  --set kubecostProductConfigs.azureStorageSecretName="myAzureConfig"
```

cc @jcharcalla @mmurph3

**Comment by AjayTripathy** [comment] 2022-10-03 21:18
@thomasvn what would you think next steps are? If there's a better way should this be removed from our configurations?

**Comment by thomasvn** [comment] 2022-10-04 17:20
Some of our next steps should include:

1. Updating all public docs to reference the `.Values.kubecostProductConfigs.cloudIntegrationSecret` when setting up Azure Cloud Integration
2. Creating internal docs about `.Values.kubecostProductConfig.azureStorageSecretName`. This includes a saved version of the old public docs. Notes about recent issues with this config. And observations on what occurs when using this config.
3. Slowly deprecating the `.Values.kubecostProductConfig.azureStorageSecretName` config from the codebase.

I can take the charge on this when time permits. Thoughts? @AjayTripathy

**Comment by AjayTripathy** [comment] 2022-10-11 12:09
I support these changes... assigned you!

**Comment by thomasvn** [comment] 2022-10-11 15:14
@AjayTripathy ACK! I will update this Github Issue as progress is made.

**Comment by bwagner3slb** [comment] 2022-11-01 13:11
I am having this issue currently.  The rate card does not connect as shown in the screen snapshot above.  When I add kubecostProductConfigs.cloudIntegrationSecret and kubecostProductConfigs.serviceKeySecretName the mounts never get created in the output from the Helm command.  running "helm template -f ./my-values-aks.yaml . "  with this in the my-values-aks.yaml

**Comment by dwbrown2** [comment] 2022-12-05 01:05
Any other outstanding work here now that #1827 is merged?!

**Comment by thomasvn** [comment] 2022-12-05 21:03
I think we can consider this issue complete! However, there is further related work that I'd like to work on for a future release:

* There are `cost-model` errors being thrown about `/var/configs/azure-storage-config.json` file missing, even though the user has set up cloud integration via `cloud-integration.json`. Fix this error message.
* Deprecate the `.Values.kubecostProductConfigs.azureStorage*` from Helm templates. Provide advance notice and monitor response. If successful, deprecate its corresponding backend code from the `cost-model` image.

**Comment by Adam-Stack-PM** [comment] 2022-12-05 21:51
@thomasvn, Awesome. Closing this issue.  When you have time please open one or two issues for the additional item proposed.

**Closed by Adam-Stack-PM** 2022-12-05 21:51 UTC
Labels: bug, v1.99

**Comment by Adam-Stack-PM** [comment] 2022-12-20 15:58
See work left to complete: https://github.com/kubecost/cost-analyzer-helm-chart/issues/1854
