### ISSUE TITLE
Why have we removed the ability to file a bug here? 

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#2563] opened 2023-09-01 16:07 UTC
### Problem Statement

As a Kubecost user, I used to be able to file a product bug in this repo. Can we share why we've taken that ability away?

### Solution Description

*

### Alternatives

*

### Additional Context

*

**Comment by chipzoller** [comment] 2023-09-09 11:51
After filing PR #2527 with a nice, graphical issue template specifically for bug reports I was told in an internal discussion by @kwombach12 that the current preferred method for raising bugs is either Kubecost Slack (#support channel) or email.

**Comment by dwbrown2** [comment] 2023-09-15 20:38
@chipzoller @kwombach12 I still think it's valuable to have the ability to directly report a bug within GH. I view that as pretty standard in community projects. I wonder what the best approach is.

**Comment by chipzoller** [comment] 2023-09-15 21:08
My suggestion would be the following approach.

* Bugs can be filed in this repo only if they pertain specifically to the Helm chart. It is commonplace for bugs to affect packaging form factors while not being applicable to the application(s) being distributed by them. If an application bug is filed, the user is directed to either Slack or email support, whichever we want. The issue is then closed as being not applicable.

* Bugs which affect the application still go to Slack or email support. Should a bug report for the Helm chart land in either location, the inverse process from above is used.

If we follow this or something close, it should ensure we have good organization and, most importantly, we don't drop anything.

**Comment by kwombach12** [comment] 2023-09-18 22:01
@chipzoller I like your suggestion here. @dwbrown2 Lets discuss how we can provide users with the best bug/issue support with the Kubecost support team. I'm sure that there are users whose preferred method of interaction is GH.

**Comment by dwbrown2** [comment] 2023-09-19 21:03
I like this proposed approach too! @chipzoller @kwombach12 let me know if you want to discuss.

**Comment by chipzoller** [comment] 2023-10-05 15:30
Closed in #2595

**Closed as completed by chipzoller** 2023-10-05 15:30 UTC
Labels: enhancement, needs-triage
