### ISSUE TITLE
UI Crashes because of high memory/cpu utilization when multiple users are logged into Kubecost (concurrency issue)

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#1881] opened 2022-12-15 21:47 UTC
**What problem are you trying to solve?**
When there are multiple users logged into the UI (in this case 5-6+), the UI crashes because of high resource utilization. This makes the UI unusable. Adding memory and cpu, rebuilding etls has not helped this issue. Customer experienced this on v1.95. Waiting on them to upgrade to v1.98+ to see how much it helps.

**Describe the solution you'd like**
1. Create more "read-only" pods that query etls that live in durable storage.
2. Create some sort of common caching view so the etls don't get queried everytime a user hits the landing page/allocations page.
3. Scale replicas of cost-analyzer pod?
4. Provide a scalable solution so multiple queries can be run against the api's concurrently by several users.

**Describe alternatives you've considered**
Have no more than 2 users logged in at a time. 

**How would users interact with this feature?**
Multiple end users would log into the UI and not experience a degraded UI or UI that's unavailable.

**Context**

Want to give ~200 developers access to the UI. 40 clusters, 4 billing reports (gcp,azure,aws,custom csv) worth of data being ingested. Will get more data points added to this issue soon.

**Comment by AjayTripathy** [comment] 2022-12-15 21:56
I'd like to look at this in v1.100

**Comment by mmurph3** [comment] 2023-01-11 18:38
@AjayTripathy any update on this and can we get it into v1.100?

**Comment by teevans** [comment] 2023-01-13 00:26
@mmurph3 - Just to confirm here, you mention the UI is crashing, is it giving a white screen? Or is the underlying pod crashing?

**Comment by ivankube** [comment] 2023-01-13 17:53
@teevans "It was the pod crashing resource limitations with 2-3 users. We did not observe this behavior in 1.98 as memory/cpu seemed to stay constant."

**Comment by AjayTripathy** [comment] 2023-01-18 09:18
Are we saying that this is a new regression in memory consumption in 1.99 @ivankube ?

**Comment by ivankube** [comment] 2023-01-18 14:47
@AjayTripathy Correction from the user - "From cursory testing with five users seems to be resolved once we upgraded to 1.98. On previous versions this would cause resource starvation". This particular user does not experience UI crash anymore.

**Comment by AjayTripathy** [comment] 2023-01-18 19:03
Cheers! Know this is an ongoing effort to continue to improve, but can we close this one out?

**Comment by mmurph3** [comment] 2023-01-19 01:41
@AjayTripathy we can close for now. Thanks!

**Closed as completed** 2023-01-19 01:41 UTC
Labels: enhancement
