### ISSUE TITLE
Cloud Cost Report - Graph area still shows "cost", when data below shows "netCost"

### ISSUE THREAD

**Issue by kc-adawson** [kubecost/cost-analyzer-helm-chart#2080] opened 2023-03-24 11:20 UTC
**Describe the bug**  

@Sean-Holcomb for visibility:

In the new images where we have AWS Net Amortized costs working, the top graph section in the Cloud Cost report still shows the "cost" and not the "netCost". Please update the Cloud Cost report graphs to use the "netCost" data.

**To Reproduce**  

Tested with 2 active trial evaluations with AWS netCosts.

**Expected behavior**  

Seeing the netCosts on both the Cloud Cost report's top and bottom section

**Comment by dwbrown2** [comment] 2023-03-24 15:53
@Sean-Holcomb would you call this P1?

Adding @Adam-Stack-PM @allyleonce for 102 issue tracking.

**Comment by Sean-Holcomb** [comment] 2023-03-24 15:57
Yeah probably P1
I am pretty sure it is just a matter of hooking up the graph to the right number.
In terms of reproduction, it would be easier to see on a GCP cluster where we actually have a netCost which is different then cost

**Comment by Adam-Stack-PM** [comment] 2023-03-29 19:28
https://kubecost.atlassian.net/browse/BURNDOWN-49

**Comment by nealormsbee** [comment] 2023-06-19 23:36
@Sean-Holcomb do you know if we're good to close out this issue and the corresponding Jira ticket https://kubecost.atlassian.net/browse/BURNDOWN-23 ?

I know we've moved away from `cost` and `netCost` in terms of cost metric types, in favor of more robust terms like `AmortizedNetCost`, `ListCost`, etc.

I'm having trouble confirming whether we get meaningful differences for `NetAmortized` and `Amortized`. Is there an easy way to confirm and potentially close this out?

**Comment by nealormsbee** [comment] 2023-06-25 20:50
cc @kc-adawson since you reported initially. I don't think this issue should be a problem anymore.

**Comment by MikeFindsThings** [comment] 2023-07-05 16:14
@nealormsbee or @kc-adawson, can we confirm if this has been solved or not?

Customer was asking for an update. I understand the implementation for this has changed slightly, but customer wanted to know if it had specifically been checked.

**Comment by kwombach12** [comment] 2023-07-06 16:47
@MikeFindsThings This should have been solved. Our default costs today are Amortized Net Costs

**Comment by nealormsbee** [comment] 2023-07-06 22:18
Agreed.

Closing this for the time being -- reopen if needed!

**Closed as completed by nealormsbee** 2023-07-06 22:18 UTC
Labels: bug, v1.103
