### ISSUE TITLE
List namespace labels in UI and allocation API results by default

### ISSUE THREAD

**Issue by mmurph3** [kubecost/cost-analyzer-helm-chart#2027] opened 2023-03-03 18:46 UTC
**What problem are you trying to solve?**
Having visibility into what labels are associated with any given aggregated kubernetes object, preferably namespace. The UX is impacted because it's hard to recall what labels are associated with a particular kubernetes objector who owns what, especially at scale.

**Describe the solution you'd like**
Show labels associated with ns and/or workloads when drilling down into the namespace's overview page or have a drop down that shows this from the overview page.

**Describe alternatives you've considered**
N/A

**How would users interact with this feature?**

Users would execute an aggregation and be able to see what labels are associated with the kubernetes object in the UI and in the json output of the api. Seeing namespace labels would be ideal and first priority.

**Comment by keithhand** [comment] 2023-03-03 22:20
Some additional information: we noticed that some namespaces seem to be getting values populated under `properties.labels` in the [demo.kubecost.xyz](https://demo.kubecost.xyz/model/allocation?window=1h&aggregate=namespace,cluster&filterNamespaces=default) environment. However, when trying to reproduce this behavior on a fresh cluster (default Kubecost settings), those values aren't populating. I noticed the `kube_namespace_labels` metric in the test environment is emitted for both the `/model/metrics` and the default deployed KSM, whereas on [demo.kubecost.xyz](https://demo.kubecost.xyz/model/prometheusQuery?query=kube_namespace_labels{namespace=%22default%22}) we are only be pulling the data from `/model/metrics`. However, I'm not sure if that is related.

**Comment by dwbrown2** [comment] 2023-03-08 04:19
cc @kwombach12 for input!

**Comment by kwombach12** [comment] 2023-03-08 17:45
I like this idea a lot! I would propose adding a section to the inspect pages (not just namespace inspect) to show which labels are associated with the selected entity.

**Comment by mmurph3** [comment] 2023-03-10 00:49
@kwombach12 we have a mock up from the same enterprise customer: https://github.com/opencost/opencost/pull/1749

**Comment by mmurph3** [comment] 2023-03-20 18:24
@kwombach12 is it possible to get this into v1.102?

**Comment by kwombach12** [comment] 2023-03-20 18:33
@mmurph3 unfortunately, code freeze for 1.102 is on Friday & we will not have enough capacity to add this. @Annalillie can you make some mocks for how this would look so we can have this ready for 1.103?

**Comment by Annalillie** [comment] 2023-03-20 18:48
@kwombach12 thanks for the tag. I absolutely can.

**Comment by mmurph3** [comment] 2023-04-27 17:12
@kwombach12 @Annalillie can we confirm this is making it into v1.103? Has it made it into the latest rc? I see the PR [here](https://github.com/opencost/opencost/pull/1789#issuecomment-1480013952).

**Comment by kwombach12** [comment] 2023-04-27 17:17
I don't believe this is making it into 103 in the UI. @ameijer Does that PR address this in the API?

**Comment by ameijer** [comment] 2023-04-27 17:18
Correct @kwombach12 - this is an API-only feature currently

**Comment by mmurph3** [comment] 2023-04-27 17:19
@ameijer nice - is this in the latest rc? rc.4

**Comment by ameijer** [comment] 2023-04-27 17:23
@mmurph3 yes, was merged before the first RC. Here is the PR with the implementation that made it in: https://github.com/opencost/opencost/pull/1857

Basically, we return all common labels/annotations in the labels/annotations field of the returned object. you will need to send includeAggregatedMetadata=true

**Comment by mmurph3** [comment] 2023-05-02 20:18
@ameijer feedback we received from a user testing:

```
We tested the namespace labels on the release candidate and we are able to see the labels on some of the namespaces but not on all the namespaces. We tried to run the below GET from postman
http://localhost:9090/model/allocation?window=3d&aggregate=namespace
```

Output:

```
"name1": {
                "name": "name1",
                "properties": {
                    "cluster": "xxxxxxxxxxxxxxxx",
                    "namespace": "name1"
                },
                "window": {
                    "start": "2023-04-29T00:00:00Z",
                    "end": "2023-04-30T00:00:00Z"
                },
                "start": "2023-04-29T00:00:00Z",
                "end": "2023-04-29T02:00:00Z",
                "minutes": 120,
                "cpuCores": 1.45,
                "cpuCoreRequestAverage": 1.45,
                "cpuCoreUsageAverage": 0.00343,
                "cpuCoreHours": 2.9,
                "cpuCost": 0.09144,
                "cpuCostAdjustment": 0,
                "cpuEfficiency": 0.00237,
                "gpuCount": 0,
                "gpuHours": 0,
                "gpuCost": 0,
                "gpuCostAdjustment": 0,
                "networkTransferBytes": 0,
                "networkReceiveBytes": 0,
                "networkCost": 0,
                "networkCrossZoneCost": 0,
                "networkCrossRegionCost": 0,
                "networkInternetCost": 0,
                "networkCostAdjustment": 0,
                "loadBalancerCost": 0,
                "loadBalancerCostAdjustment": 0,
                "pvBytes": 5368709120,
                "pvByteHours": 10737418240,
                "pvCost": 0.0011,
                "pvs": {
                    "cluster=xxxxxxxxxxxxxxxx": {
                        "byteHours": 10737418240.000002,
                        "cost": 0.001095890410958904
                    }
                },
                "pvCostAdjustment": 0,
                "ramBytes": 2863771648,
                "ramByteRequestAverage": 2863771648,
                "ramByteUsageAverage": 193583509.68306,
                "ramByteHours": 5727543296,
                "ramCost": 0.02255,
                "ramCostAdjustment": 0,
                "ramEfficiency": 0.0676,
                "externalCost": 0,
                "sharedCost": 0,
                "totalCost": 0.11509,
                "totalEfficiency": 0.01527,
                "rawAllocationOnly": null,
                "proportionalAssetResourceCosts": null
            },
```

Waiting on feedback/output from the following query to validate whether it still occurs:

`curl "http://localhost:9090/model/allocation?window=1d&includeAggregatedMetadata=true"`

**Comment by ameijer** [comment] 2023-05-02 20:40
Hi Mike- 

There are a few caveats to the way we implemented this. We abandoned the idea of a unique field and take the intersection of all labels/annotations of the objects in the aggregation. What this means in the context of your specific note (where the customer is aggregating by namespace) is the following:

1. If any pods have the same label/annotation keys as the namespace, those namespace labels will be overwritten in favor of the pod ones
2. This logic is an intersection of all resource labels/annotations together. So, in the case where the namespace has label `label1: foo` , pod 1 has the label `label1: foo`, then `label1: foo` will be returned. If there is a different label key/value anywhere, none of these labels will be returned. So continuing the example, if there is a second pod, pod 2 with label `label1: bar`, then there is no intersection and no label will be returned 

I hope this helps - might give a few things to check out on the user's end

**Comment by jsonmp-k8** [comment] 2023-05-03 15:19
What was the idea behind doing that ? The reason why we request this feature was, when we aggregate by namespace, we need the namespace label to identify the owner of the namespace and do the chargeback to the owner. With this implementation, we will be loosing those information and this feature itself will not help us.

**Comment by ameijer** [comment] 2023-05-03 17:52
Hello @jsonmp-k8!

The idea was to present the information using the existing fields and present alongside pod metadata. If this is not acceptable, allow me to propose an alternative implementation: 

1. we introduce new fields into the allocation properties object, `namespaceLabels` and `namespaceAnnotations`, that will hold the labels from the namespace of whatever the object is, exclusively. 
2. These will always be present and on. When you aggregate, the intersection of these labels will be used in the aggregated object. For example, if you aggregate by, say, cluster, and one allocation has namespacelabels: `label1: x, label2: y` and another allocation from a different namespace has namespaceLabels: `label1: x, label3: z`, then the resulting allocation will have the namespaceLabels: `label1:x`

Looking forward to your feedback on this matter!

**Comment by jsonmp-k8** [comment] 2023-05-03 17:55
We are building a cost reporting tool that would hit the kubecost API, so we wanted to aggregate by namespace and charge the entire cost of the namespace to the namespace owner. The only way to know the namespace owner is to get the namespace label.

**Comment by ameijer** [comment] 2023-05-03 18:06
@jsonmp-k8 sounds good - that NamespaceLabels field I proposed above would be guaranteed to have all the labels of the namespace in the use case you describe. Let me go work something up now

**Comment by jsonmp-k8** [comment] 2023-05-04 00:31
Will the above change that you suggested work with this query?
```
curl "http://localhost:9090/model/allocation?window=1d&includeAggregatedMetadata=true"
```

**Comment by ameijer** [comment] 2023-05-04 13:12
@jsonmp-k8

In the interest of full disclosure, what I am proposing below still requires internal review and might change between now and what we finally ship:

I think with this change we would move to always including this information by default. Here's an example from my experimental installation with this feature:

Our cert-manager namespace: 
```
$ kubectl get ns cert-manager -o yaml
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2022-10-12T20:21:48Z"
  labels:
    kubernetes.io/metadata.name: cert-manager
    name: cert-manager
  name: cert-manager
```

And my call to the allocations API on my experimental feature testing setup 

```
$ curl 'http://localhost:9003/allocation?window=1d&aggregate=namespace' -s | jq '.data[0]."cert-manager"'
{
  "name": "cert-manager",
  "properties": {
    "cluster": "gcp-dev-1-alex",
    "container": "cert-manager",
    "controllerKind": "deployment",
    "namespace": "cert-manager",
    "namespaceLabels": {
      "kubernetes_io_metadata_name": "cert-manager",
      "name": "cert-manager"
    }
  },
  "window": {
    "start": "2023-05-03T14:00:00Z",
    "end": "2023-05-03T15:00:00Z"
  },
  "start": "2023-05-03T14:00:00Z",
  "end": "2023-05-03T15:00:00Z",
  ...
}
```

As you can see, there is a new namespaceLabels field with the labels from the cert-manager namespace object. These would be present regardless of what the pod labels were - they only hold the namespace labels (and there is a corresponding field, namespaceAnnotations, that would have any annotations from the cert manager namespace) 

We would remove the includeAggregatedMetadata parameter and just always return these labels/annotations to you.

I have the open source portion of these changes in a draft PR here: https://github.com/opencost/opencost/pull/1896 

Would this meet the requirements of your intended use case?

**Comment by mmurph3** [comment] 2023-06-05 18:20
@ameijer enterprise customer statement:

We were looking for something like this:
`http://localhost:9090/model/allocation?window=3d&includeAggregatedMetadata=true&aggregate=namespace`

Where the cost is aggregated by namespace and namespace labels are displayed when we get the aggregated view

@jsonmp-k8 - any more context you'd like to add?

**Comment by mmurph3** [comment] 2023-06-07 00:52
@ameijer i know it's late but customer confirmed this works for their use case. Can we get it in v1.104 ? 

cc @kwombach12

**Comment by ameijer** [comment] 2023-06-07 12:16
@mmurph3 I think we can, release got delayed a day it looks like. 

cc @cliffcolvin

**Comment by ameijer** [comment] 2023-06-07 20:40
@mmurph3 not sure I will get the reviews I need by CoB today. We can ship a patch release if we can't get in by EoD, I am actively working on chasing this down

**Comment by passionInfinite** [comment] 2023-06-28 20:28
If we can get those labels info on the requestSizingV2 API that will be really helpful for our Team to produce savings based grouping of the response based on the labels from the requestSizingV2 API.

**Comment by chipzoller** [comment] 2024-05-09 15:46
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.

**Closed as completed by chipzoller** 2024-05-09 15:46 UTC
Labels: enhancement
