### ISSUE TITLE
Clearly Display Alert Configurations in the Kubecost Frontend.

### ISSUE THREAD

**Issue by AjayTripathy** [kubecost/cost-analyzer-helm-chart#1074] opened 2021-09-21 06:28 UTC
**Describe the bug**
The new values.yaml settings for alerts are sometimes not reflected on the Kubecost frontend, if they were introduced as new concepts after the original namespace-only based alerts. We should deprecate the old frontend alerts.html / place it maintenance mode and update it to cleanly parse the new values.yaml.

**Comment by dwbrown2** [comment] 2021-09-22 23:50
My understanding of the issue is that we added support for new alerts via YAML and haven't yet fully updated the alerts frontend to reflect this. Is that an accurate understanding?

If I remember correctly, @nealormsbee has already made some great progress on a new alerts page.

**Comment by nealormsbee** [comment] 2021-09-23 15:55
@dwbrown2 that's right. It's very similar to the current alerts page in terms of look and functionality, but uses React components and is slightly better styled IMO. Missing a few minor features like sending a "test" alert email.

Hit pause on it because we were talking about rethinking the design in a bigger way. Maybe a good topic to revisit at the start of Q4?

**Comment by kbrwn** [comment] 2021-11-23 16:29
Resolved by v1.88.0

**Closed by kbrwn** 2021-11-23 16:29 UTC
Labels: bug
