### ISSUE TITLE
The orphaned resources page errors out when missing access to all AWS regions

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#2167] opened 2023-04-20 22:09 UTC
**Describe the bug**  
If using an account that doesn't have access to every AWS region, the orphaned resources page details are inaccessible (screenshot below). 

**To Reproduce**  
1. Add permissions necessary to access resources on this page (`DescribeAddresses` and `DescribeVolumes`)
2. Update the AWS account not to have specific region access ([us-east-1 link](https://us-east-1.console.aws.amazon.com/iamv2/home?region=us-east-1#/account_settings))
3. Navigate to `/orphaned-resources` and see the error.
4. Checking AWS Cloudtrail logs will reveal errors for disabled regions. This also includes `us-gov` regions for all users outside of the US who can't access these.

**Expected behavior**  
The orphaned resources savings page should display the information it can gather and not try to pull (or ignore) the regions it doesn't need.

**Screenshots**
![image](https://user-images.githubusercontent.com/43491549/233495270-f81331bd-5aea-4072-8b8e-6ade8d95b3cd.png)

**Collect logs (please complete the following information):**
https://github.com/kubecost/cost-analyzer-helm-chart/issues/1989#issuecomment-1434730341 - Contains a potentially relevant log that appears when this occurs.

**Please share the support case, if any**  
[ZD ticket](https://kubecost.zendesk.com/agent/tickets/3779https://kubecost.zendesk.com/agent/tickets/3779)

**What impact will this have on your ability to get value out of Kubecost?**
Every AWS user can use the orphaned resources savings page without needing global AWS access.

**Comment by kwombach12** [comment] 2023-04-21 13:56
@AjayTripathy @teevans do we need access to all regions by design for some reason?

**Comment by teevans** [comment] 2023-04-21 14:00
We'll need access to show all resources, but we should only show the ones we have access to, and just ignore the ones we don't. Let's file this on the burndown.

**Comment by kwombach12** [comment] 2023-04-21 14:04
done!

**Comment by saweber** [comment] 2023-08-31 17:08
Resolved with https://github.com/opencost/opencost/pull/2112

**Closed as completed by saweber** 2023-08-31 17:08 UTC
Labels: bug, needs-triage
