### ISSUE TITLE
Allocation standard API returns 0 adjustments when using Step 1h 

### ISSUE THREAD

**Issue by praveenkumar0566** [kubecost/cost-analyzer-helm-chart#2373] opened 2023-06-17 08:17 UTC
**Describe the bug**  
Allocation standard API returns 0 adjustments when using 1h `step`. For the same window and time, the adjustments return non-zero values for the 1-day step.

0 adjustments when using 1h `step`
`cpuCoreUsageAverage":0.16437,"cpuCoreHours":2.20668,"cpuCost":0.04122,"**cpuCostAdjustment":0,**
`

Non- zero adjustment when using 1d step
`{"code":200,"data":[{"cluster-one":{"name":"cluster-one","properties":{"cluster":"cluster-one"},"window":{"start":"2023-05-11T00:00:00Z","end":"2023-05-12T00:00:00Z"},"start":"2023-05-11T00:00:00Z","end":"2023-05-12T00:00:00Z","minutes":1440,"cpuCores":2.19436,"cpuCoreRequestAverage":2.11,"cpuCoreUsageAverage":0.16575,"cpuCoreHours":52.66454,"cpuCost":0.9829,"cpuCostAdjustment":0.10924,
`

**To Reproduce**  
1. Make sure to change `etlHourlyStoreDurationHours` to `121`
2.  [] (https://demo.kubecost.xyz/model/allocation?window=2023-05-11T00:00:00Z,2023-05-12T00:00:00Z&accumulate=false&step=1h&aggregate=cluster&idle=false)
3. Error or issue

The adjustments for 1 hr step shows 0

**Expected behavior**  

1hour step allocation API should non-zero adjustments like 1 day adjustments for the same window and time.

**Screenshots**  

[1fva81lhn6q6g7-allocation_standard_1h_cluster (1).txt](https://github.com/kubecost/cost-analyzer-helm-chart/files/11778331/1fva81lhn6q6g7-allocation_standard_1h_cluster.1.txt)

Make sure to rename file to .json

**Comment by udidn** [comment] 2023-06-20 14:27
Hey - I opened the [original support ticket](https://kubecost.slack.com/archives/CLFV60Y90/p1684054764560079) reporting this issue.
A few clarifications:

1/ The reaosn for changing `etlHourlyStoreDurationHours` to `121` is to make sure that data in the queried window will be reconciled to begin with.
I'm using EKS cluster, and the my Kubecost is integrated with CUR, and due to CUR's update frequency, there can be gap in the reconciled data for up to 48 hours.
Since the default value of `etlHourlyStoreDurationHours` is `49`, it means that by default I can query only for window before 49 hours ago, which can risk in returning non-reconciled data to begin with, which is counter-productive for reproducing this issue.
Changing `etlHourlyStoreDurationHours` to `121` allows me to query for window beyond 49 hours ago, which makes sure that the data will be reconciled, meaning that if the adjustments are still returned as 0, we rule the root cause of having no data in CUR for this window yet.

2/ For the same window being queried with `step=1h`, I also queried it with `step=1d`, which returns non-zero adjustments.
This confirms that the data is reconciled, and that there's a specific issue with getting reconciled data (non-zero adjustments) from the Allocation standard API when using `step=1h`.

**Comment by jessegoodier** [comment] 2023-06-20 15:16
My understanding is that 1h stores are never reconciled, only daily. 
@nikovacevic can confirm.

**Comment by nikovacevic** [comment] 2023-06-20 15:17
As far as I know, that's correct @jessegoodier

**Comment by nikovacevic** [comment] 2023-06-20 15:19
There are two reasons for that:
1. Cost and usage reports do not provide real-time data. The earliest we can generally guarantee that data will be available is 48h ago.
2. Cost and usage reports also do not always provide hourly data—so daily is usually the lowest resolution possible to achieve.

**Comment by udidn** [comment] 2023-06-20 15:44
1. I'm not sure I understand how this is related to the fact that 1h store doesn't return reconcile data.
Once the data is available (48h ago at the earliest), you can retrieve it, irrespective of the granularity.
2. For the line items that Kubecost needs (EC2, EBS, data transfer), it returns hourly data, always - at least to the best of my knowledge.
As long as you configure the CUR with hourly granularity when you create it, you'll have hourly line items.
If you know of a case where CUR doesn't return hourly line items, even when the CUR is configure with hourly granularity, I'd be happy to know the specific use-case.
The Athena query that Kubecost executes uses `DATE_TRUNC('day',line_item_usage_start_date)`, which makes Athena return daily line items.
If you remove the `DATE_TRUNC` function and just use `line_item_usage_start_date`, Athena will return hourly line items (as long as CUR is configured with hourly granularity), and you can use those line items to reconcile into 1h steps in Kubecost.
The tradeoff is performance, of course - but I think it's up to the users to decide if they want hourly granularity in expense of performance. It can be controlled via a Helm value.

Is there anything that I'm missing?

**Comment by nikovacevic** [comment] 2023-06-20 16:15
In my previous message, I shared why the product decision was made to do it this way, and can confirm that the feature is working as intended. We do welcome feature requests if you believe the product should function differently. In the meantime, I am of the opinion that we can close this ticket, as there is no bug here.

**Comment by udidn** [comment] 2023-06-20 16:35
No problem, thanks

**Closed as completed** 2023-06-21 01:02 UTC
Labels: bug
