### ISSUE TITLE
GKE Cost recommendations unable to find bigquery dataset 

### ISSUE THREAD

**Issue by cheddarwhizzy** [kubecost/cost-analyzer-helm-chart#2447] opened 2023-07-18 21:39 UTC
**Describe the bug**  
I'm attempting to get resource recommendations working

**To Reproduce**  

- Install helm chart version 1.104.1 with `clusterController.enabled=true`
- Enable `GKE usage metering` and set the correct dataset ID (e.g. `wk_qa_gke_usage`)
- Set `kubecostProductConfigs` and `clusterController`
  ```
  clusterController:
    enabled: true
    logLevel: debug
    secretName: kubecost-gcp-key

  kubecostProductConfigs:
    projectID: "my-gcp-project-id"
    clusterProfile: development
    bigQueryBillingDataDataset: "my-gcp-project-id.wk_qa_gke_usage"
    gcpSecretName: "kubecost-gcp-key"
    clusterName: <gke-cluster-name>
    clusterAccountID: "my-gcp-project-id"
  ```

**Expected behavior**  
The `kubecost-cost-analyzer` pod should be able to fetch recommendations but fails to find that dataset
```
{"level":"error","time":"2023-07-18T21:14:17.749249091Z","message":"ETL: CloudUsage[my-gcp-project-id/my-gcp-project-id.wk_qa_gke_usage]: Build[IYnAa]: QueryCloudUsage error: googleapi: Error 404: Not found: Dataset my-gcp-project-id:my-gcp-project-id was not found in location US, notFound"}
```

The following works with the GCP service account key activated
```
gcloud --project my-gcp-project-idalpha bq datasets describe wk_qa_gke_usage

access:
- role: WRITER
  specialGroup: projectWriters
- role: WRITER
  userByEmail: service-abcd123456@gcp-sa-bigquerydatatransfer.iam.gserviceaccount.com
- role: OWNER
  specialGroup: projectOwners
- role: OWNER
  userByEmail: abcd123456@cloudservices.gserviceaccount.com
- role: READER
  specialGroup: projectReaders
creationTime: '1610468552142'
datasetReference:
  datasetId: wk_qa_gke_usage
  projectId: my-gcp-project-id
etag: readacted
id: my-gcp-project-id:wk_qa_gke_usage
kind: bigquery#dataset
labels:
  goog-dm: k8s-cluster
lastModifiedTime: '1659987420412'
location: US
selfLink: https://bigquery.googleapis.com/bigquery/v2/projects/my-gcp-project-id/datasets/wk_qa_gke_usage
type: DEFAULT
```

K8s secret has both keys. The GCP SA has owner and bigquery admin roles. 
```
kgsec kubecost-gcp-key -o yaml

apiVersion: v1
data:
  compute-viewer-kubecost-key.json: <REDACTED>
  service-key.json: <REDACTED>
kind: Secret
metadata:
  name: kubecost-gcp-key
  namespace: kubecost
type: Opaque
```

**Comment by kirbsauce** [comment] 2023-07-18 22:29
Thanks for the submission, @cheddarwhizzy !  We'll review and get back to you.

**Comment by kirbsauce** [comment] 2023-07-19 15:06
@cheddarwhizzy , would you mind trying our latest version, 1.105?  It contains a fix for recommendations related to google cloud.  Hoping this will address your issue but if not we'll keep digging.

**Comment by cheddarwhizzy** [comment] 2023-07-21 23:16
I did bump the chart version to `1.105.0` but I still get no recommendations

**Comment by kirbsauce** [comment] 2023-07-24 15:28
And I assume you received the same error w/105?

**Comment by cheddarwhizzy** [comment] 2023-07-27 22:57
So I'm not getting the error anymore, my `bigQueryBillingDataDataset` is now `wk_qa_gke_usage.gke_cluster_resource_usage` instead of the `gcp-project.wk_qa_gke_usage` - I assume that's the correct table name for this. However, I'm still getting no recommendations for an apps/v1 deployment in k8s 1.24. The UI fails with 
```
Applying recommendation partially failed:
clusterid/namespace/controllerkind/controllername <cluster-name>/<namespace>pod/<pod-name> plan cannot be applied because the controller kind is not supported.
```

**Comment by kirbsauce** [comment] 2023-07-27 23:32
@cheddarwhizzy let me run this by one of the engineers and get back to you.

**Comment by kirbsauce** [comment] 2023-07-28 15:11
Hey @cheddarwhizzy!  Engineering feels there are a few things that could be attributing to this error.  I'll just drop them here and we can discuss...

Based on the error message, it appears the problem is applying request right-sizing recommendation using the 1-click sizing automation feature (via Cluster Controller). It's mentioned this is “for an apps/v1 deployment” but the error message indicates that 1-click automation is being used to apply a recommendation to an “uncontrolled pod” (a Pod without a controller like a Deployment). As the error message indicates, 1-click sizing for uncontrolled Pods is currently unsupported.

What might be happening:

1. The intent is to apply recommendations for a deployment, but as a side effect is also applying recommendations for uncontrolled pods because filtering has not set up on the request sizing page. The error message is “partially failed” — that means that other recommendations, if shown on the page at the time of sizing, were probably applied successfully
2. Kubecost is incorrectly ingesting data, leading to a Pod which belongs to a Deployment not being marked as such (very unlikely)
3. There is confusion that an uncontrolled Pod belongs to a Deployment (also seems very unlikely)

We feel the first situation is the most likely.

**Comment by cheddarwhizzy** [comment] 2023-08-08 17:22
Even after drilling down the request sizing page to a single pod, I'm still getting the same error
```
error="failed to create sizing patch for workload 'coupon-api-v2/deployment/coupon-api-v2': failed to get recommendation for '{Namespace:coupon-api-v2 ControllerKind:deployment ControllerName:coupon-api-v2 ContainerName:coupon-api-v2}' '{Window:2d TargetUtilizationCPU:<nil> TargetUtilizationMemory:<nil>}': received no recommendation"
```

I'll also note:
- I'm on chart version 1.105.1
- filtering by `controllerKind` set to `deployment` or `Deployment` results in `Error loading request sizing recommendations` in the UI. Same for `ControllerName`. Only pods ever show up on the sizing page

**Comment by kwombach12** [comment] 2023-08-08 19:44
@jcharcalla Can you help us resolve this?

**Comment by jcharcalla** [comment] 2023-08-08 20:35
@cheddarwhizzy 

> Only pods ever show up on the sizing page

Are you saying on the `/request-sizing` page you do not see any items listed in the format of `<namespace>\deployment:<deployment name>`?
Can you share a screenshot of what you are seeing?

As for the error `'{Window:2d TargetUtilizationCPU:<nil> TargetUtilizationMemory:<nil>}'`, what profile are you selecting?

**Comment by cheddarwhizzy** [comment] 2023-08-08 20:55
> Are you saying on the /request-sizing page you do not see any items listed in the format of <namespace>\deployment:<deployment name>?

Correct. If I filter `ControllerKind=daemonset` I see those. Just not any deployments or statefulsets. Seems to be only pods and daemonsets

<img width="1472" alt="Screenshot 2023-08-08 at 1 47 18 PM" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/5047844/7b4c4a8c-8b3d-4d07-a85f-44492a579028">
<img width="1354" alt="Screenshot 2023-08-08 at 1 48 34 PM" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/5047844/c6c6ffd2-e4f5-4b63-be79-7e1a155f38c0">

Using profile `Development` - `Production` and `High Availability` also do not work

**Comment by jcharcalla** [comment] 2023-08-08 21:14
The `coupon-api-v2` is expected to be part of a deployments, correct? So if you do `kubectl get deployment -n coupon-api-v2` it's listed?

If that is the case then it seems as if Kubecost may be missing data, bullets 2 and 3 from Kirbsauces reply.

>2. Kubecost is incorrectly ingesting data, leading to a Pod which belongs to a Deployment not being marked as such (very unlikely)
>3. There is confusion that an uncontrolled Pod belongs to a Deployment (also seems very unlikely)

Do you have any special configuration in terms of Prometheus, Cadvisor, Kube-state-metrics, or node_exporter?

**Comment by cheddarwhizzy** [comment] 2023-08-09 18:59
> The coupon-api-v2 is expected to be part of a deployments, correct? So if you do kubectl get deployment -n coupon-api-v2 it's listed?

Yes

I thought the recommendations would come from the bigquery dataset, not from Prometheus. The `prometheus-server-endpoint` in the `kubecost-cost-analyzer` ConfigMap points to the correct URL - `http://vmsingle-vmstack.victoria-metrics.svc.cluster.local:8429` and I can successfully curl `http://vmsingle-vmstack.victoria-metrics.svc.cluster.local:8429/metrics` from the kubecost namespace. 
<img width="820" alt="Screenshot 2023-08-09 at 11 48 32 AM" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/5047844/be8e1fcc-2450-4886-b259-8018b132d35e">


I'm assuming this is the issue here:

<img width="1463" alt="Screenshot 2023-08-09 at 11 53 06 AM" src="https://github.com/kubecost/cost-analyzer-helm-chart/assets/5047844/0e010222-2c20-4431-b72d-3011d4de9748">

**Comment by jcharcalla** [comment] 2023-08-09 19:53
The recommendation would come from a combination of metrics data and cloud integration billing info. Identifying the pod as part of the deployment would be done via metrics.

Given it looks like you are using Victoria Metrics, I would not expect the Prometheus self scrape to pass... that could also explain the Kubecost CPU recording rule. My understanding is with the recent version KSM is no longer a requirement.

With Victoria Metrics we have encountered issues in the past where queries were failing due to memory or other limits imposed by Victoria Metrics. This could explain missing metrics. These would be visible in the `cost-model` container logs of the `cost-analyzer` pod. The typical solution is to increase the `kubecostModel.etlResolutionSeconds`. See this doc for more info: https://docs.kubecost.com/install-and-configure/advanced-configuration/resource-consumption#lower-query-resolution

For the cloud integration error. Additional info on what is failing should be shown in the `cost-model` container logs shortly after the pod starts. This is typically a permissions issue or table name mismatch.

**Comment by chipzoller** [comment] 2024-05-02 12:00
Closing, stale.

**Closed as completed by chipzoller** 2024-05-02 12:00 UTC
Labels: bug
