### ISSUE TITLE
Chart does not template with Argo CD

### ISSUE THREAD

**Issue by abdennour** [kubecost/cost-analyzer-helm-chart#3623] opened 2024-08-29 20:30 UTC
### Kubecost Helm Chart Version

3.12.1

### Kubernetes Version

1.26

### Kubernetes Platform

OpenShift

### Description

"helm template cost-analyzer" does not work due to server-side validation in _helpers.tpl ( lookup function) 

### Steps to reproduce

1. `helm add repo kubecost https://url/to/helm/repo`
2. Use old values.v1.yaml
3. `helm template kubecost/cost-analyzer -f values.v1.yaml --version 2.3.4`
4. Keep following the warning and fix incompatible values with v2.
5. Until no clear thing to fix, but just this general error: 

```log
Error: execution error at (kubecost-federated/charts/costanalyzer/templates/NOTES.txt:2:4): 

SSO with RBAC is enabled.
Note that Kubecost 2.x has significant architectural changes that may impact RBAC.
This should be tested before giving end-users access to the UI.
Kubecost has tested various configurations and believe that 2.x will be 100% compatible with existing configurations.
Refer to the following documentation for more information: https://docs.kubecost.com/install-and-configure/install/kubecostv2

When ready to upgrade, add `--set upgrade.toV2=true`.

Use --debug flag to render out invalid YAML
``` 

### Expected behavior

We expected the chart to render to the Full YAML without error when running `helm template`, and to work client-side(without dependencies with the current KUBECONFIG)

### Impact

The Current Kubecost is too outdated ( 1.x.x), and we wanna run another instance of Kubecost v2.3.4 . Even it's new instance with new namespace, `helm template` does not work.

### Logs

```Shell
Error: execution error at (kubecost-federated/charts/costanalyzer/templates/NOTES.txt:2:4): 

SSO with RBAC is enabled.
Note that Kubecost 2.x has significant architectural changes that may impact RBAC.
This should be tested before giving end-users access to the UI.
Kubecost has tested various configurations and believe that 2.x will be 100% compatible with existing configurations.
Refer to the following documentation for more information: https://docs.kubecost.com/install-and-configure/install/kubecostv2

When ready to upgrade, add `--set upgrade.toV2=true`.

Use --debug flag to render out invalid YAML
```

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by chipzoller** [comment] 2024-08-29 20:35
This is not a bug as the additional checks are needed as part of the upgrade process. You may need to enable [these values](https://github.com/kubecost/cost-analyzer-helm-chart/blob/v2.3/cost-analyzer/values.yaml#L249-L252) in the new chart.

**Comment by chipzoller** [comment] 2024-08-30 15:50
Closing this issue but let us know if you still have issues after enabling those values.

**Closed as completed by chipzoller** 2024-08-30 15:50 UTC

**Comment by abdennour** [comment] 2024-08-31 13:09
thanks for pointing out the values of `cicd`
