### ISSUE TITLE
Out of cluster costs - Azure

### ISSUE THREAD

**Issue by Zenmodai** [kubecost/cost-analyzer-helm-chart#414] opened 2020-04-23 12:12 UTC
We are using Kubecost with an Azure Kubernetes Cluster and we would like to track the costs of Azure specific out of cluster resources (e.g. databases) with Kubecost as well.
I checked the [documentation](http://docs.kubecost.com/getting-started#out-of-cluster), but currently there is no mention of out of cluster cost allocation/tracking for Azure.

Is this not yet implemented/supported or just the documentation missing?

**Comment by dwbrown2** [comment] 2020-04-23 21:42
Hi @Zenmodai! This is currently on our roadmap. We're actively discussing prioritization on this feature now. Reach out to us at team@kubecost.com if you want to discuss timeline/priority.

**Comment by Zenmodai** [comment] 2020-06-19 06:05
Hi @dwbrown2 Maybe you can give an update here as well. When is this feature currently planned in the roadmap? I am sure others, who use Azure, would be interested in this as well.

**Comment by dwbrown2** [comment] 2020-06-19 14:52
@Zenmodai this effort has been scoped but under development. We will share an update when it's completed, but please feel free to reach out to our team if this is a high priority for you.

**Comment by AjayTripathy** [comment] 2020-06-19 20:31
I've filed https://github.com/kubecost/cost-model/issues/450 to track in the other repo

**Comment by pierluigilenoci** [comment] 2021-01-22 12:03
Any news about this?

**Comment by dwbrown2** [comment] 2021-01-26 01:16
Current expectation is that this work will be started in our next sprint!

**Comment by sylus** [comment] 2021-02-01 19:20
Happy to be an evaluator for this if need anyone to take a look :D

**Comment by dwbrown2** [comment] 2021-02-01 23:59
Thanks, William! We currently have @Sean-Holcomb looking at this now. Working to find the right integration points with the Azure team. Let us know if anyone has a suggested contacts!

**Comment by dwbrown2** [comment] 2021-02-11 05:02
This feature just launched in Beta in our v1.74 release! Initial documentation [here](https://docs.google.com/document/d/1xb20INwYrlV6NDUtb9kMza92W_l30gm9GS65tnP_O7U/edit). Reach out to us at team@kubecost.com if you want to learn more or if we can help in anyway.

**Comment by pierluigilenoci** [comment] 2021-02-11 12:06
@Sean-Holcomb trailing comma left here: https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/templates/azure-storage-config-secret.yaml#L16 (JSON is not well-formed).

**Comment by pierluigilenoci** [comment] 2021-02-11 15:57
@dwbrown2 I configured the integration and Kubecost is able to gather cost from the subscription of the cluster. 

During parsing, however, I noticed a very high number (many thousands) of error messages logs like these: 
```
E0211 15:48:20.848889       1 log.go:17] [Error] Could not parse item tags invalid character ':' after top-level value
E0211 15:48:20.848907       1 log.go:17] [Error] Could not parse item tags invalid character ':' after top-level value
E0211 15:48:20.848925       1 log.go:17] [Error] Could not parse item tags invalid character ':' after top-level value
E0211 15:48:20.848945       1 log.go:17] [Error] Could not parse item tags invalid character ':' after top-level value
E0211 15:48:20.848961       1 log.go:17] [Error] Could not parse item tags invalid character ':' after top-level value
E0211 15:48:20.848976       1 log.go:17] [Error] Could not parse item tags invalid character ':' after top-level value
E0211 15:48:20.849000       1 log.go:17] [Error] Could not parse item tags invalid character ':' after top-level value
E0211 15:48:20.849016       1 log.go:17] [Error] Could not parse item tags invalid character ':' after top-level value
E0211 15:48:20.849028       1 log.go:17] [Error] Could not parse item tags invalid character ':' after top-level value
E0211 15:48:20.849043       1 log.go:17] [Error] Could not parse item tags invalid character ':' after top-level value
E0211 15:48:20.849065       1 log.go:17] [Error] Could not parse item tags invalid character ':' after top-level value
E0211 15:48:20.849090       1 log.go:17] [Error] Could not parse item tags invalid character ':' after top-level value
E0211 15:48:20.849111       1 log.go:17] [Error] Could not parse item tags invalid character ':' after top-level value
E0211 15:48:20.849125       1 log.go:17] [Error] Could not parse item tags invalid character ':' after top-level value
E0211 15:48:20.849144       1 log.go:17] [Error] Could not parse item tags invalid character ':' after top-level value
```

**Comment by Zenmodai** [comment] 2021-02-11 16:11
@pierluigilenoci What did you do for the integration? I set up the export of the cost report and created the secret, added the secret name to the deployment, but Kubecost is not showing the out of cluster Azure costs in the dashboard. There are also no log messages regarding the reading of the reports or any errors, that something is wrong. Did you do something else?

**Comment by pierluigilenoci** [comment] 2021-02-11 16:24
I created the secret, added the following option in the helm chart, and created the export following this [guide](https://docs.google.com/document/d/1xb20INwYrlV6NDUtb9kMza92W_l30gm9GS65tnP_O7U/edit) and this [guide](https://docs.microsoft.com/en-us/azure/cost-management-billing/costs/tutorial-export-acm-data?tabs=azure-portal).
```yaml
azureStorageSecretName: "azure-storage-config"
```

**Comment by Zenmodai** [comment] 2021-02-11 16:33
Hmm... strange, I followed the same guides, but nothing seems to happen regarding this new feature.

**Comment by evertonmc** [comment] 2021-02-11 16:35
> Hmm... strange, I followed the same guides, but nothing seems to happen regarding this new feature.

same here

**Comment by Sean-Holcomb** [comment] 2021-02-11 17:14
@evertonmc @Zenmodai Were you able to verify the creation of the first export file on your Azure Storage account. Additionally do you still see the banner at the top of your Assets page about OOC not being set up?

**Comment by Sean-Holcomb** [comment] 2021-02-11 17:49
@pierluigilenoci from what I can tell you have some nested JSON in your tags column, can you confirm and if possible give me an example

**Comment by Sean-Holcomb** [comment] 2021-02-11 21:06
@pierluigilenoci it doesn't actually seem to be nested JSON but malformed JSON. I was only able to replicate the exact error you are getting with a trailing ':' on one of my rows tags following the closing bracket. If this is not the case for you, an example of a failing row would be instructive.

**Comment by andreb89** [comment] 2021-02-12 07:43
We are now one step further, after recreating the Azure cost export. But we are now getting parse errors as well in the cost-model container log.

`E0212 07:21:11.907060       1 log.go:17] [Error] failed to parse usage date: <InvoiceSectionName>`

InvoiceSectionName seems to be our company name for the invoice.

**Comment by pierluigilenoci** [comment] 2021-02-12 08:46
@Sean-Holcomb I assume you're talking about the export CSV file.
Our tags are like this, no nested JSON. I checked all rows.

```csv
"""akelius_environment"": ""devops"",""akelius_project"": ""k8s"",""akelius_team"": ""ops"",""aksEngineVersion"": ""v0.47.0-aks-gomod-at-aks"",""creationSource"": ""aks-aks-system201116-28105498-vmss"",""orchestrator"": ""Kubernetes:1.18.8"",""poolName"": ""system201116"",""resourceNameSuffix"": ""28105498"""
```

I am not able to distinguish which lines are generating the problem because the logs give no indication about it. 

The only JSON inside the report is like this:
```csv
"{  ""ResourceType"": ""Bandwidth"",  ""UsageResourceKind"": ""DataTrOut:Linux_IaaS_Canonical|Standard_D2s_v3|b71f870a-6d7f-4fe9-b2aa-92bce2ad8a9e|4fd886c4-ae05-4d22-8b3a-3bd7085ab73e:Linux:Running"",  ""DataCenter"": ""AMZ07"",  ""NetworkBucket"": ""External"",  ""PipelineType"": ""v1""}"
```

What else can I do to help you debug the problem?

**Comment by Sean-Holcomb** [comment] 2021-02-12 17:21
@pierluigilenoci Given your error message we can rule out the nested JSON issue, I am specifically talking about the JSON in the "Tags" column of your CSV. The JSON is you provided is well formed so shouldn't be causing an issue. Specifically I am looking for rows that do not have a "MeterCategory" of "Virtual Machines" or "Storage". To replicate the error that you showed I had to add JSON to the "Tags" column which looked like this.
```"{  ""ResourceType"": ""Bandwidth"",  ""UsageResourceKind"": ""DataTrOut:Linux_IaaS_Canonical|Standard_D2s_v3|b71f870a-6d7f-4fe9-b2aa-92bce2ad8a9e|4fd886c4-ae05-4d22-8b3a-3bd7085ab73e:Linux:Running"",  ""DataCenter"": ""AMZ07"",  ""NetworkBucket"": ""External"",  ""PipelineType"": ""v1""}:"```
Note the trailing colon. This is not necessarily the only way to trigger that exact error message, but a possibility. Either way, I am hoping to figure out why Azure would be putting malformed JSON into CSV or why our JSON parser is failing. 

A final note, this error is non fatal to the row that is being looked at it just prevents the cost from receiving labels that are generated from tags that you have set. That being said the costs of these rows are still showing up in your report

**Comment by Sean-Holcomb** [comment] 2021-02-12 17:37
@andreb89 The CSV parser should be agnostic to column ordering. It creates a map of the headers to column number. So when it looks for the "UsageDateTime" it is looking for the column with that string in the header. That being said does your CSV have any additional rows at the top of the file? Additionally the Algorithm grabs the most recent CSV in each month folder. It sounds like you tried uploading a modified file to the folder, is that correct?

**Comment by andreb89** [comment] 2021-02-15 07:24
@Sean-Holcomb The top of our exported CSV looks as follows:
`﻿Name der Abteilung (DepartmentName),Name des Kontos (AccountName),ID des Kontobesitzers (AccountOwnerId),Abonnement-GUID (SubscriptionGuid),Name des Abonnements (SubscriptionName),Ressourcengruppe (ResourceGroup),Ressourcenstandort (ResourceLocation),UsageDateTime (UsageDateTime),ProductName (ProductName),Kategorie der Verbrauchseinheit (MeterCategory),MeterSubcategory (MeterSubcategory),ID der Verbrauchseinheit (MeterId),Name der Verbrauchseinheit (MeterName),Region der Verbrauchseinheit (MeterRegion),Maßeinheit (UnitOfMeasure),UsageQuantity (UsageQuantity),Ressourcensatz (ResourceRate),PreTaxCost (PreTaxCost),Kostenstelle (CostCenter),Genutzter Dienst (ConsumedService),ResourceType (ResourceType),InstanceId (InstanceId),Tags (Tags),OfferId (OfferId),Zusätzliche Informationen (AdditionalInfo),Dienstinformation 1 (ServiceInfo1),Dienstinformation 2 (ServiceInfo2)`

So initially we already got the parse error, so next I tried to manually adjust the CSV, but it didn't really help, since then I got another parse error. So something in general seems to not work here. The unedited CSV export does not work and results in a parse error:

`E0212 07:21:11.907060 1 log.go:17] [Error] failed to parse usage date: <DepartmentName>`

**Comment by andreb89** [comment] 2021-02-15 08:16
@Sean-Holcomb In addition to the bug @pierluigilenoci already mentioned before, I found another problem.

> @Sean-Holcomb trailing comma left here: https://github.com/kubecost/cost-analyzer-helm-chart/blob/master/cost-analyzer/templates/azure-storage-config-secret.yaml#L16 (JSON is not well-formed).

When you specify a secret for the azure storage name (azureStorageSecretName), but also use serviceKeySecretName or createServiceKeySecret, then in [cost-analyzer-deployment-template.yaml - lines 259 and 263](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L259) you are mounting the /var/secrets path twice, which results in the following deployment error:

`##[error]Error: Deployment.apps "pau-monitor-kubecost-cost-analyzer" is invalid: spec.template.spec.containers[0].volumeMounts[2].mountPath: Invalid value: "/var/secrets": must be unique`

**Comment by Sean-Holcomb** [comment] 2021-02-15 19:08
@andreb89 Okay that makes a lot of sense, unfortunately it looks like both the naming and row ordering is not going to be consistent between locales and Azure account types, so that does pose a challenge to me. As for the error message it just seems like it is unsuccessful in finding the UsageDateTime column which is strange because you listed that column as having the same name. The error is being generated by this 
```
usageDateTime, err := time.Parse(AzureLayout, record[headerMap["UsageDateTime"]])
if err != nil {
	log.Errorf("failed to parse usage date: '%s'", record[headerMap["UsageDateTime"]])
	continue
}
```
Where AzureLayout is "2006-01-02" and record is a []string for the csv row and headerMap is map[string]int which matches column name to column number. What was the other parse error? The specific column headers that I am using as of right now are "MeterCategory", "UsageDateTime", "InstanceId", "AdditionalInfo", "Tags", "PreTaxCost", "SubscriptionGuid", "ConsumedService" and "ResourceGroup". If you can see if using these exact headers help, and I will think about a long term solution for this issue. 

As for your second comment that is meant as an alternate method of configuration that is still a WIP thank you for pointing it out though. For now just stick with the one configuration outlined [here](https://docs.google.com/document/d/1xb20INwYrlV6NDUtb9kMza92W_l30gm9GS65tnP_O7U/edit?usp=sharing) 

Please let me know if you are seeing any other error messages or have any other insights you think I should know based off of what I have told you here.

**Comment by Sean-Holcomb** [comment] 2021-02-15 19:14
@andreb89 "Name der Abteilung (DepartmentName)", did you add the text in parentheses or is that how it shows up in the header?

**Comment by andreb89** [comment] 2021-02-15 19:22
@Sean-Holcomb This is how it shows up. The export job was created with Azure CLI. If I create the export with the portal, then I do not have the German column titles, but then I cannot create exports which include the UsageDateTime. The different types of reports I can create from the portal do not have this column. 
So I can only use the exports from the job created by Azure CLI and those have the German and English title columns.

**Comment by Sean-Holcomb** [comment] 2021-02-15 19:25
@andreb89 Ok that is great news, I will start working on a fix for you

**Comment by pierluigilenoci** [comment] 2021-02-16 05:57
@Sean-Holcomb I will share the complete CSV via Slack.

**Comment by andreb89** [comment] 2021-02-16 08:01
@Sean-Holcomb I tried what you suggested and manually removed all header columns, which you currently aren't using and also edited the ones you are using to fit your header titles, e.g. "Abonnement-GUID (SubscriptionGuid)" => "SubscriptionGuid"

Afterwards there were no further parse errors for the header titles themselves, rather I am now getting the same error as mentioned before:
`E0216 07:43:53.838875       1 log.go:17] [Error] Could not parse item tags invalid character ':' after top-level value`

An example of a tag value is: `"created-by": "azure"`
Maybe the quotation marks are the problem in the parsing of the tags?

But now we know, that the locales of the headers and the ordering is currently the problem for our default generated reports. After manually changing the report headers, at least I can now see the data in the kubecost asset dashboard.

**Comment by Sean-Holcomb** [comment] 2021-02-16 16:48
@andreb89 currently looking at @pierluigilenoci 's CSV that he sent on Slack and seeing that none of the strings in his tags column have {} around the outside, which seems to be the things casing the JSON parser issues. Is that how your tags column looks also?

**Comment by andreb89** [comment] 2021-02-16 16:57
@Sean-Holcomb Yes, our tags column looks the same. All look like this: `"environment": "staging","project": "pau"` without any {} around the outside.

**Comment by Sean-Holcomb** [comment] 2021-02-18 21:16
Fixes have been merged and will be in the next release. Please let me know if you have any additional feedback.

**Comment by pierluigilenoci** [comment] 2021-02-22 18:34
@Sean-Holcomb I found a new bug. https://github.com/kubecost/cost-analyzer-helm-chart/issues/783
Could you please fix this before the new release?

**Comment by pierluigilenoci** [comment] 2021-02-24 18:34
@Sean-Holcomb now the CSV appears to be digested correctly. I'll send you a copy of the logs via Slack.

**Comment by andreb89** [comment] 2021-02-25 09:44
@Sean-Holcomb I found a new bug. Currently, if you create the azure-storage-config secret with the helm chart, the secret is only added to the volumes (see lines: 107-111 in [cost-analyzer-deployment-template.yaml](https://github.com/kubecost/cost-analyzer-helm-chart/blob/dea4d554188defce4fa61ef19d3d12b420224463/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L107)). But the secret is not mounted in the actual container deployment. The else if `{{- else if .Values.kubecostProductConfigs.azureStorageCreateSecret }}` is missing for the volumeMounts section ([line 260](https://github.com/kubecost/cost-analyzer-helm-chart/blob/dea4d554188defce4fa61ef19d3d12b420224463/cost-analyzer/templates/cost-analyzer-deployment-template.yaml#L260)).

**Comment by Sean-Holcomb** [comment] 2021-02-25 23:24
@andreb89 I have merged your suggested fix on the storage config so the next version should support that method of configuration.

I will look into adding more logging for the CSV processing as you have suggested. The ETL runs every 3 hours if you want to trigger a rebuild you can use the endpoint `/model/etl/assets/rebuild?window=all&commit=true`.

In terms of showing OOC data on days which do not have in cluster data, that feature is currently unavailable, but it is a known behavior.

**Comment by andreb89** [comment] 2021-02-26 14:13
@Sean-Holcomb Thanks for the endpoint, it is a great help during testing. 
But the issue still remains, that the data/graph that is shown in the asset dashboard is unclear. Like I mentioned in the post above, as you can see here:
![Screenshot from 2021-02-26 15-02-05](https://user-images.githubusercontent.com/78923723/109309503-a6b5b400-7843-11eb-97f9-54c2a05a76e4.png)
This is from this morning, after I manually exported a newly created cost report. So the data for yesterday the 25th should be complete. But what the dashboard shows is only part of the cost for yesterday 25th, specifically only Kubernetes, no out of cluster costs. That's why I asked, if maybe there is something wrong here regarding the dates? I checked the reports, there are no cost entries already for the 26th (today), which makes sense I guess. So maybe what is shown in the graph as costs for 25th should be 26th (today) ? Since for today only Kubernetes costs are available, but no other out of cluster costs yet.

I hope you can clear this up. Maybe there is actually still a bug here, since something doesn't add up.

**Comment by AjayTripathy** [comment] 2021-03-02 01:37
Hi @andreb89 -- I believe we set the date ranges on our end to skip data less than 2d old because it may be incomplete. Regarding what day is shown when, all data should be in UTC.

**Comment by andreb89** [comment] 2021-03-02 16:07
@AjayTripathy But that is a strange behaviour. If I look at the costs, I wouldn't expect that the last 2 days are missing. I am not sure why the data from one day ago should not be complete, but even if it isn't, it should still be shown. Otherwise  some of the time range options don't really make sense.

**Comment by dwbrown2** [comment] 2021-03-04 21:34
@andreb89 I believe Sean and Ajay did this because Azure can provide partial data during this 48-hour time window. 

@Sean-Holcomb I think it could be ok to display partial assets data during this window. We however would not want to do reconciliation on partial data because this is likely to skew metrics heavily. 

Thoughts?

**Comment by Sean-Holcomb** [comment] 2021-03-05 06:05
@dwbrown2 That is exactly right, and that is how it is currently functioning with OOC showing everything that is available in the most current report and reconciliation excluding the partial data because of the skew that it causes. 

@andreb89 I think that you are experience 2 issues, a time shift on the in cluster costs due to the data being displayed in UTC, you can see this in your weekend being offset in your earlier post. The other is like you suggested the Azure data might not be syncing properly with the k8s generated data. If you could give me some more information that might be helpful for solving this issue. For starters what timezone are you in? If you are willing to provide one of the export CSV and the time it was generated along with matching assets page, that would be helpful too, feel free to reach out to me on slack.

**Comment by andreb89** [comment] 2021-03-10 09:11
@Sean-Holcomb My timezone is CET (Central European Time). Currently I also use the parameter kubecostModel.utcOffset to set "+01:00" for the timezone. I hope this helps. Regarding the cost export, I don't think I can share it at the moment.

**Comment by andreb89** [comment] 2021-03-12 09:27
@dwbrown2 Could please elaborate on why it takes 48 hour to display the complete Azure out of cluster costs? I haven't found any information about this.

@Sean-Holcomb I just updated to the new version 1.76.0 and at least for me, the problem regarding the time shift in the displayed cluster costs remains. I am not sure what the problem is. You mentioned, that the data being displayed is in UTC, why should this be a problem and result in a time shift of the costs? I am using the parameter to offset UTC and in the reports there are only days specified. Is there something else that I have to configure regarding timezones?

For further information, I added a more specific example. The following image should display the Asset costs from 8th March to 12th March (today). But it shows from 7th - 11th. At the far right there is an empty column, which I assume should be for the 12th, but it is completely empty. So is there something missing in the configuration or is this behavior a bug?
![Screenshot from 2021-03-12 10-23-38](https://user-images.githubusercontent.com/78923723/110919956-1a17f500-831d-11eb-9da5-8d9d207fa822.png)

**Comment by Sean-Holcomb** [comment] 2021-03-12 21:51
@andreb89 In response to your first question. The 48 hour window is only for the adjustment column on in cluster costs. That is because cost data takes a day to be exported and additionally there is a day when the costs for the most recent day are incomplete we wait a full 48 hours before trying to use them to adjust Kubecost's in cluster estimates. The reasoning here is that if the cost data for the day is incomplete, it will over adjust prices for that day downward. For OOC costs there is no such window, the most recent costs in the exported cost CSV are displayed whenever Kubecost pulls in that data.

Given your timezone the offset you are seeing is definitely a bug I have created an issue for you here https://github.com/kubecost/cost-analyzer-helm-chart/issues/816. If you feel like I have missed something please add it in.

**Comment by dwbrown2** [comment] 2021-03-13 00:36
Now that we've confirmed the core functionality works, @Sean-Holcomb shall we close this in favor or #816?

**Comment by Sean-Holcomb** [comment] 2021-03-13 00:41
@dwbrown2 sounds good.

@all please tag me in any additional Azure issues you create, and hopefully I can be helpful.

**Closed by Sean-Holcomb** 2021-03-13 00:41 UTC
Labels: good first issue
