### ISSUE TITLE
Key duplication in kubecost-metrics-deployment-template.yaml

### ISSUE THREAD

**Issue by mortenmj** [kubecost/cost-analyzer-helm-chart#1322] opened 2022-03-22 15:29 UTC
**Describe the bug**

Similar to #1150 there is a key duplication where the app label applied from kubeMetricsName conflicts with commonLabels.
This causes kustomize to fail.

**To Reproduce**

Run yamllint against helm manifests of templates/kubecost-metrics-deployment-template.yaml
grep key-duplication

gz#1548

**Comment by jcharcalla** [comment] 2022-03-22 22:54
@mortenmj Can you provide details on what version you are using  and the error from kustomize?

I was unable to reproduce this using with v1.91.2 and `yamllint 1.26.3`. 
```$ yamllint cost-analyzer-helm-chart-1.91.2/cost-analyzer/templates/kubecost-metrics-deployment-template.yaml | grep key-duplication```

It may also be helpful if you can provide a copy of the `kubecost-metrics-deployment-template.yaml` file you are using.

**Comment by jcharcalla** [comment] 2022-03-25 22:24
Thank you for your submission, it has been merged and should be included in an upcoming release.

**Closed by jcharcalla** 2022-03-25 22:24 UTC
Labels: bug
