### ISSUE TITLE
Allow use of `config.prefix` in `kubecostModel.etlBucketConfigSecret` secret by bumping to Thanos 0.27

### ISSUE THREAD

**Issue by LaikaN57** [kubecost/cost-analyzer-helm-chart#1758] opened 2022-10-24 23:57 UTC
**What problem are you trying to solve?**

I am trying to have multiple clusters backup ETL data to the same S3 bucket using `kubecostModel.etlBucketConfigSecret`. However when using a secret like this:

```yaml
apiVersion: v1
kind: Secret
type: Opaque
stringData:
  object-store.yaml: |
    type: S3
    config:
      bucket: "my-bucket"
      prefix: "my-prefix"
      endpoint: "s3.amazonaws.com"
      region: "us-east-1"
      insecure: false
      signature_version2: false
      put_user_metadata:
        "X-Amz-Acl": "bucket-owner-full-control"
```

I get the following warning:

```log
0000-00-00T22:57:58.831642422Z WRN ETL: failed to create bucket storage: create S3 client: yaml: unmarshal errors:
  line 4: field prefix not found in type storage.S3Config
```

However if we look at similar documenation to the [doc referenced](https://guide.kubecost.com/hc/en-us/articles/4407601811095-ETL-Backup#:~:text=This%20configuration%20secret%20follows%20the%20same%20layout%20documented%20for%20Thanos%20here%3A%20https%3A//thanos.io/v0.21/thanos/storage.md), in these [similar docs](https://github.com/thanos-io/objstore#s3:~:text=The%20field%20prefix,which%20blocks%20came) we can see that a `config.prefix` key is mentioned. (NOTE: I think the documentation actually has an error and the `prefix` key should be under the `config` key.)

**Describe the solution you'd like**

Extend the unmarshalling functionality for the `storage.S3Config` type to be able to handle the `config.prefix` key. This may be as simple as just updating a dependency to a newer version (not sure).

**Describe alternatives you've considered**

None.

**How would users interact with this feature?**

Users would be able to include a `config.prefix` key in their `kubecostModel.etlBucketConfigSecret` secret to be able to select a custom prefix inside of a custom bucket.

**Comment by LaikaN57** [comment] 2022-10-24 23:57
I am not 100% sure if this is the correct repo top open this issue against. If there is a better place, please LMK.

**Comment by LaikaN57** [comment] 2022-10-25 00:07
...and just to confirm, I also tried moving the `prefix` key up a level (as it was in the doc example originally) and got the same warning:

```log
0000-00-00T00:03:59.443141449Z WRN ETL: failed to create bucket storage: parsing config YAML file: yaml: unmarshal errors:
  line 12: field prefix not found in type storage.StorageConfig
```

**Comment by kirbsauce** [comment] 2022-10-27 17:52
Hi @LaikaN57!  Sorry for the delayed response.  We're in the process of triaging this enhancement request and, in parallel, trying to determine if there is any workaround for you.

**Comment by LaikaN57** [comment] 2022-10-27 17:58
@kirbsauce No worries. My current workaround is just to use multiple buckets. This is a bit annoying but works well enough for my use-case.

At minimum, if you/your team could just advise if this issue can be solved with just a version bump of some dependency or if this requires far more work, that will help me plan a possible re-arch timeline on my side. Thanks!

**Comment by thomasvn** [comment] 2022-10-27 19:53
Hi @LaikaN57! Thanks for bringing this up! I agree that it would be convenient to have the `prefix` key so that all ETL backups can be managed in a single bucket.

I believe your recommendation is correct! This issue could probably be solved with a version bump.

Currently our Thanos subchart is on v0.24 [as shown here](https://github.com/kubecost/cost-analyzer-helm-chart/blob/56b880ce2bd4c2092648a446ff6110c02ccf0592/cost-analyzer/charts/thanos/Chart.yaml#L2). However when looking at Thanos's changelog, it seems that they don't introduce the `prefix` key until v0.27 [as shown here](https://thanos.io/v0.21/thanos/changelog.md/#v0270httpsgithubcomthanos-iothanostreerelease-027---20220705).

I don't currently have a timeline of when this version bump will happen and how long it will take to implement/test (as there have been a moderate amount of customizations made to the Thanos subchart).

cc @Adam-Stack-PM

**Comment by LaikaN57** [comment] 2022-10-27 23:38
Ah ok, this seems to clear things up a bit. I wasn't sure if the config was actually going to thanos. The kubecost docs seemed to indicate that the config was just "thanos-like" in schema (and presumably picked up by some other thing for use). But yeah if this is just going to thanos then that might open up some options for me.

**Comment by AjayTripathy** [comment] 2022-10-31 18:45
Great candidate for 1.99, thank you for investigating. @thomasvn , can you just make the changes in the helm chart soon and we'll roll them out to nightly to let them bake?

**Comment by srpomeroy** [comment] 2022-11-07 18:26
Do we run Thanos in nightly?

**Comment by AjayTripathy** [comment] 2022-11-09 16:35
No-- we'll want to scale test #1776 -- see notes there.

**Comment by mbolt35** [comment] 2022-11-09 19:46
@LaikaN57 is correct here. This particular support has nothing to do with the thanos dependency, as we modeled our configs such that we didn't create a completely new backup auth scheme. However, we _do_ want to move both the thanos dependency and update the config support in the same release (the idea is that they should stay the same). 

Just wanted to explicitly call out that updating the thanos dependency will not resolve this issue for backups, we'll need to also add prefix support in our `storage` implementations.

**Comment by thomasvn** [comment] 2022-11-09 20:17
Thanks for clarifying @mbolt35! I began suspecting the same thing yesterday evening.

After bumping the Thanos image from v0.24 -> v0.29 in our subchart then doing some testing on my cluster, I began to realize that although [ETL Backups require](https://guide.kubecost.com/hc/en-us/articles/4407601811095-ETL-Backup#step-1-create-storage-configuration-secret) an `object-store.yaml` with the same yaml schema as Thanos ... it doesn't depend on any parts of Thanos for uploading ETL stores to cloud storage.

Therefore bumping the Thanos version would be an insufficient fix. We'd need to make some changes to the `kubecost-cost-model` image.

**Comment by LaikaN57** [comment] 2022-11-10 02:02
@thomasvn Add me as a contributor on the internal repo and I'll write the code for you guys 😉

To be clear, for this/my issue, I am only interested in providing a bucket with prefix for ETL backup. I have no requirement to also use this configuration for Thanos itself, although I could see how it would be useful/helpful to keep both config "flavors" in-sync.

**Comment by LaikaN57** [comment] 2022-11-10 02:13
@thomasvn @AjayTripathy Also, if either of you can advise if the `storage` implementation modification work can still be targeted for `v1.99`, that would be helpful for planning on my side. Not sure what t-shirt size that work is. I'm guessing `S` just to add another key to an existing structure presumably.

**Comment by thomasvn** [comment] 2022-11-10 17:43
I'll defer the decision on whether this can go into v1.99 to @AjayTripathy and @Adam-Stack-PM.

Thanks @LaikaN57 for clarifying that you only need `prefix` for ETL Backups and not for Thanos storage! By design, I think we would like to keep both of those object storage interfaces in sync. A fix for this would require a change to OpenCost's [`storage`](https://github.com/opencost/opencost/tree/831c65c364156dc048da50bbb4814a9da9583dfb/pkg/storage) package (originally forked from Thanos and modified).

**Option 1** would be to follow Thanos’s implementation of `prefix`, and create a similar [`prefixed_bucket.go`](https://github.com/thanos-io/objstore/blob/main/prefixed_bucket.go) wrapper for our storage package.

**Option 2** would be to transition our entire `storage` package to instead use Thanos’s new [`objstore`](https://github.com/thanos-io/objstore#thanos-object-storage-client) Go client. While this would be a big rework, I anticipate this would reduce lots of future maintenance. Thoughts @mbolt35?

**Comment by LaikaN57** [comment] 2022-11-10 19:59
Ah, my bad. I didn't think I found this in `opencost` before when I looked. Thanks for the breadcrumbs.

**Comment by thomasvn** [comment] 2022-11-11 16:45
@LaikaN57 No problem! Because the size of the work is larger than anticipated, it's likely that this feature won't be completed for `v1.99`. However I'll keep you updated on its status as it's discussed!

**Comment by AjayTripathy** [comment] 2022-12-09 06:19
Sorry this missed 1.99, but we can commit to this in 1.100

**Closed** 2023-02-02 21:33 UTC
Labels: enhancement, P1, v1.100
