### ISSUE TITLE
Allocation API has GPU costs when GPU count is 0

### ISSUE THREAD

**Issue by keithhand** [kubecost/cost-analyzer-helm-chart#1389] opened 2022-04-26 23:40 UTC
**Describe the bug**
When using a custom pricing model, GPU prices can be assigned to \_\_idle\_\_ costs, even though the GPU count for the node is 0. 

**To Reproduce**
1. Create a cluster with no GPU-enabled nodes.
2. Install Kubecost with `kubecostProductConfigs.customPricesEnabled = true` in the values.yaml. The default pricing values will work to demonstrate the bug. 
3. Navigate to the Cost Allocation page and see \_\_idle\_\_ GPU costs.

**Expected behavior**
GPU costs should be $0.

**Screenshots**
![image](https://user-images.githubusercontent.com/43491549/165409729-3c33f771-f5ce-40ad-8bd8-9d5f931d639f.png)

**Comment by AjayTripathy** [comment] 2022-04-27 17:55
I wanted to note that a quick workaround here is to set GPU prices to 0 in your default pricing settings.

**Comment by AjayTripathy** [comment] 2022-04-27 17:56
I will do a bit of digging to see if I can help narrow down the cause, but assigning to @dramich since it's a good chance to dive into a messy bit of the code base :)

**Comment by AdamStack18** [comment] 2022-05-03 22:16
@dramich any update here?

**Closed** 2022-05-06 20:06 UTC
Labels: bug, v1.94
