### ISSUE TITLE
Fix Advanced Reports aggregation and filtering in v1.102.1

### ISSUE THREAD

**Issue by ivankube** [kubecost/cost-analyzer-helm-chart#2165] opened 2023-04-20 20:03 UTC
**Describe the bug**  
 v1.101.2 --> v1.102.1 upgrade broke saved reports

Additionally, filters do not work in v1.102.1 Advanced Reports

**To Reproduce**  
Steps to reproduce not-working filters:
1. Create Advanced Report with aggregation by service and filter by one other2. Observe extra outputs 

Steps to reproduce the issue with saved reports:
1. Create a report via YAML with aggregate by service in v1.101.2
3. Upgrade to v1.102.1
4. Open the saved report and observe incorrect aggregation by the owner

**Expected behavior**  
Saved reports work as they should. Filters provide the correct outcome.

**Screenshots**  
[Filter is not working](https://demo.kubecost.xyz/advanced-reporting?agg=service&cloudJoinLabel=label%3Akubernetes_service&filters=W3sicHJvcGVydHkiOiJzZXJ2aWNlIiwidmFsdWUiOiJuZ2lueC1wbHVzLW5naW54LWluZ3Jlc3MifV0%3D):
![Screenshot 2023-04-20 at 3 56 19 PM](https://user-images.githubusercontent.com/97049075/233474326-a1aafc3d-7f33-46df-b0ff-cb568ac87d85.png)

**Please share the support case, if any**  
https://kubecost.zendesk.com/agent/tickets/3900 has a recording of these issues.

**Comment by kwombach12** [comment] 2023-04-20 20:47
@ivankube can you please file these bugs separately?

**Comment by michaelmdresser** [comment] 2023-04-21 19:56
@kwombach12 ~~I don't have a lot of context here, but I wouldn't be surprised if the upgrade problem and the general filter problem are caused by the same underlying problem. I suggest we treat this issue as "filters are broken in advanced reports" and then come back later to test the upgrade path.~~ rereading, I'm not sure if this is true. I still think we should prioritize filters first.

**Comment by michaelmdresser** [comment] 2023-04-24 19:38
Split to 2 Jira tickets for work tracking internally:
- Advanced Report filters: https://kubecost.atlassian.net/browse/BURNDOWN-80
- Saved Report upgrade problem: https://kubecost.atlassian.net/browse/BURNDOWN-86

**Comment by nickcurie** [comment] 2023-04-24 23:04
Could not reproduce [BURNDOWN-80](https://kubecost.atlassian.net/browse/BURNDOWN-80). See ticket for testing steps followed.

[BURNDOWN-80]: https://kubecost.atlassian.net/browse/BURNDOWN-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by kwombach12** [comment] 2023-04-25 13:11
@ivankube are you still able to repro? Can we close this issue?

**Comment by ivankube** [comment] 2023-04-25 13:23
@kwombach12 Please use this link to repro: https://demo.kubecost.xyz/advanced-reporting?agg=service&cloudJoinLabel=label%3Akubernetes_service&filters=W3sicHJvcGVydHkiOiJzZXJ2aWNlIiwidmFsdWUiOiJuZ2lueC1wbHVzLW5naW54LWluZ3Jlc3MifV0%3D

**Comment by chipzoller** [comment] 2024-05-09 15:31
Closing, stale. For any future enhancements or bugs which do not pertain specifically to the Helm chart, please log them in the [features-bugs](https://github.com/kubecost/features-bugs/) repo.

**Closed as completed by chipzoller** 2024-05-09 15:31 UTC
Labels: bug
