### ISSUE TITLE
[Bug] Secondaries Aggregator can't be turned off.

### ISSUE THREAD

**Issue by passionInfinite** [kubecost/cost-analyzer-helm-chart#3172] opened 2024-02-23 00:22 UTC
### Kubecost Helm Chart Version

v2.0.2 and v2.1.0 both

### Kubernetes Version

v1.27.7

### Kubernetes Platform

AKS

### Description

If I have `kubecostAggregator.enabled: false` and `kubecostAggregator.deployMethod: disabled` . The nginx.conf file fails to process successfully and thus keeps the frontend pod restarting.

The reason for nginx.conf not get parsed successfully is because upstream for aggregation is not defined due to disabling of aggregator but the endpoints in the conf file still tries to use it which nginx throws error saying [emer] aggregator host not defined in upstream.

I believe all those endpoints server should be configured based on the aggregator settings. Currently they are hardcoded expecting it to have aggregator running.

Example: https://github.com/kubecost/cost-analyzer-helm-chart/blob/v2.1.0/cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml#L309

### Steps to reproduce

1. Disable aggregator and also make deployMethod as `disabled`.
2. Deploy the kubecost. The frontend pod will keep on restarting failing to parse the nginx.conf file.

### Expected behavior

I expect even if the aggregator is disabled everything else should work as is.

### Impact

We can't really use v2.x version.

### Logs

```Shell
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration                                                                                            │
│ /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/                                                                                                                   │
│ /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh                                                                                                       │
│ 10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)                                                                               │
│ /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh                                                                                                               │
│ /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh                                                                                                           │
│ /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh                                                                                                           │
│ /docker-entrypoint.sh: Configuration complete; ready for start up                                                                                                                           │
│ 2024/02/23 00:21:55 [emerg] 1#1: host not found in upstream "aggregator" in /etc/nginx/conf.d/default.conf:94                                                                               │
│ nginx: [emerg] host not found in upstream "aggregator" in /etc/nginx/conf.d/default.conf:94
```

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/ISSUE_GUIDELINES.md) and this is a bug impacting only the Helm chart.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by AjayTripathy** [comment] 2024-02-26 01:53
cc @michaelmdresser thoughts here?

**Comment by michaelmdresser** [comment] 2024-02-26 17:55
@AjayTripathy this is a well-defined bug (thanks @passionInfinite!). I'm guessing that this install path slipped through the cracks when releasing 2.0; this was intended to be a supported configuration.

**Comment by passionInfinite** [comment] 2024-02-26 19:27
@michaelmdresser  any workarounds until this gets fixed? Happy to contribute to move forward. We really want to move to v2.x with our internal releases.

**Comment by michaelmdresser** [comment] 2024-02-26 20:56
To workaround it, you can edit the `nginx.conf` file in the frontend container (either with `kubectl exec` or before installing the configmap in the cluster) to remove the offending references to the `aggregator` upstream.

A contribution would involve identifying the parts of https://github.com/kubecost/cost-analyzer-helm-chart/blob/develop/cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml that must be modified when `aggregator.depoyMethod=disabled` to remove the references to the `aggregator` upstream -- a quick glance reveals these as a likely candidate: https://github.com/kubecost/cost-analyzer-helm-chart/blob/bb92e85ffd303fa0063f687728f3931cbf07cde8/cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml#L283-L328

It's debatable whether or not the frontend container should even exist if Aggregator is disabled -- it is almost certain that the FE will be in a degraded state because it does not have its expected API server available. A more sensible thing might be to disable the frontend entirely when Aggregator is disabled.

**Comment by michaelmdresser** [comment] 2024-02-26 20:56
@kwombach12 for tracking

**Comment by AjayTripathy** [comment] 2024-02-27 00:10
@williamkubecost was possibly going to take a shot?

**Comment by passionInfinite** [comment] 2024-02-27 00:39
@AjayTripathy Just created a PR kubecost/cost-analyzer-helm-chart#3184

**Comment by AjayTripathy** [comment] 2024-02-27 00:54
Thank you!! Maybe @williamkubecost can help test/review kubecost/cost-analyzer-helm-chart#3184 ?

**Comment by ghost** [comment] 2024-02-27 01:32
@passionInfinite was a little faster than me! more than happy to review 😄

**Comment by passionInfinite** [comment] 2024-02-27 12:19
Thank you @williamkubecost !! Let me know if you need anything from my end 😄

**Comment by srpomeroy** [comment] 2024-02-28 17:21
I'm unsure how it impacts this, but there is a helm value for disabling components on secondary deployments.
`federatedETL.agentOnly=true`
https://github.com/kubecost/cost-analyzer-helm-chart/blob/bb92e85ffd303fa0063f687728f3931cbf07cde8/cost-analyzer/values.yaml#L3012

It disables Grafana, forecasting service, and the frontend.

**Comment by passionInfinite** [comment] 2024-02-28 18:26
@srpomeroy Yes it disables but then cluster controller doesn't work as it looks for backend apis and only the cost-model pod is running and nginx is not available. Check https://github.com/kubecost/features-bugs/issues/90

**Closed as completed** 2024-03-01 18:14 UTC
Labels: bug, needs-triage

**Comment by ravnalexquinn** [comment] 2024-04-12 14:17
@williamkubecost 

Hi, noting here that in v2.2.1 the issue of referencing an 'aggregator' upstream is still present. 

This section of the nginx.conf still populates by default if oidc or saml are enabled:
```
        location /auth {
            proxy_pass http://aggregator/isAuthenticated;
        }
```

It's coming from this part of the frontend configmap template: https://github.com/kubecost/cost-analyzer-helm-chart/blob/v2.2.1/cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml#L355

Is it intended to require the aggregator if saml or oidc are enabled?

**Comment by AjayTripathy** [comment] 2024-04-17 09:42
I believe it is; cc @jessegoodier to confirm.

**Comment by jessegoodier** [comment] 2024-04-17 11:33
> @williamkubecost
> 
> Hi, noting here that in v2.2.1 the issue of referencing an 'aggregator' upstream is still present.
> 
> This section of the nginx.conf still populates by default if oidc or saml are enabled:
> 
> ```
>         location /auth {
>             proxy_pass http://aggregator/isAuthenticated;
>         }
> ```
> 
> It's coming from this part of the frontend configmap template: https://github.com/kubecost/cost-analyzer-helm-chart/blob/v2.2.1/cost-analyzer/templates/cost-analyzer-frontend-config-map-template.yaml#L355
> 
> Is it intended to require the aggregator if saml or oidc are enabled?

Thanks for the question @ravnalexquinn 
Can you clarify what the goal is?

If I'm following this issue correctly, there was a question on how to disable all optional services on an agent (agentlOnly=true)?

Are you saying that you have a SAML/OIDC config that you are also using for agents?

**Comment by passionInfinite** [comment] 2024-05-13 15:30
@jessegoodier  If we turn off aggregator on secondaries can we use the kubescaler on secondaries?

**Comment by jessegoodier** [comment] 2024-05-22 13:19
> @jessegoodier If we turn off aggregator on secondaries can we use the kubescaler on secondaries?

clusterController is a local cluster only utility. 
You can run kubecost on the local cluster and also ship the federated metrics. We are happy to help with this.

**Comment by passionInfinite** [comment] 2024-07-04 13:00
@jessegoodier Sorry for missing this. Can we run aggregator as read only for ONLY Secondary cluster metrics?

**Comment by jessegoodier** [comment] 2024-07-10 00:49
This is an interesting use case, but I'm 90% sure that if you set federated true and add the federated-store while running the secondary with kubecostAggregator as single pod-
it should only send that cluster's metrics to the store while not reading the store (and acting as a primary).

does that make sense?
