### ISSUE TITLE
500 error when requesting /metrics: error(s) occurred: * duplicate label names

### ISSUE THREAD

**Issue by jessegoodier** [kubecost/cost-analyzer-helm-chart#2179] opened 2023-04-24 18:07 UTC
---
# For reproducible bugs, please provide the following

**Describe the bug**  
500 error when requesting kubecost:9090/metrics:
```
duplicate label names
```

**To Reproduce**  

We are not sure what setting or environment variable is causing the issue. 

**Screenshots**  
```
>kubectl exec -i -t --namespace kubecost-agent \
deployment/kubecost-cost-analyzer -c cost-analyzer-frontend -- \
curl http://localhost:9003/metrics -v
*   Trying 127.0.0.1:9003...
* Connected to localhost (127.0.0.1) port 9003 (#0)
> GET /metrics HTTP/1.1
> Host: localhost:9003
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< Vary: Origin
< X-Content-Type-Options: nosniff
< Date: Fri, 21 Apr 2023 22:27:38 GMT
< Content-Length: 115
< 
An error has occurred while serving metrics:

2 error(s) occurred:
* duplicate label names
* duplicate label names
* Connection #0 to host localhost left intact
```

We have a debug log in slack if needed. It doesn't have anything useful from what I can tell.

**Comment by AjayTripathy** [comment] 2023-04-24 18:45
https://github.com/prometheus-community/stackdriver_exporter/pull/153/files

I can't reproduce this but it seems like we should review the metrics emissions pipeline to make sure our label additions are deduping correctly.

**Comment by kwombach12** [comment] 2023-04-24 19:27
ticket raised: https://kubecost.atlassian.net/browse/BURNDOWN-82

**Comment by AjayTripathy** [comment] 2023-04-24 19:33
@thomasvn is going to take a stab!

**Comment by thomasvn** [comment] 2023-04-27 02:05
As an update, I'm working to build a debug image which disables metric emission, and instead prints all the metrics it would have emitted.

**Comment by thomasvn** [comment] 2023-05-02 19:13
Update:

* User is no longer seeing the "duplicate label names" error when running `gcr.io/kubecost1/cost-model:prod-1.103.0-rc.7`
* Unclear what resolved the issue. Is it the new image/release? Or maybe the duplicate label is no longer in the underlying data?

**Comment by kwombach12** [comment] 2023-08-01 14:27
@thomasvn @jessegoodier  are we good to close this issue

**Comment by jessegoodier** [comment] 2023-08-01 18:10
yes, thanks for tidying up.

**Comment by nikovacevic** [comment] 2023-08-21 17:37
We were able to repro this one. It happens when pod labels exist that are different, but they sanitize to the same label name; e.g.
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
  labels:
    app: test
    app.kubernetes.io/name: test-pod
    foo-bar: test1
    foo_bar: test2
```
Should be a reasonably quick one to fix.

**Closed as completed** 2023-08-21 20:57 UTC
Labels: bug, needs-triage

**Comment by haak** [comment] 2023-08-24 15:44
Hi I am now running helm chart version 1.105.2 and still seeing the 
```
An error has occurred while serving metrics:

duplicate label names
```

Do i need to wait for another chart update before i see the bugfix
Thanks

**Comment by kwombach12** [comment] 2023-08-24 16:02
@nikovacevic correct me if I'm wrong, but I believe @haak you can expect the fix to be in 1.106

**Comment by nikovacevic** [comment] 2023-08-24 16:10
That is correct

**Comment by haak** [comment] 2023-08-24 16:51
I gave 1.106.0-rc.11 a test and it fixed the issue. I will move back to 1.105 until full release. Thanks for the help.

**Comment by jessegoodier** [comment] 2023-08-24 20:08
@haak rc.11 (now .12) is very stable. If you need it for the label issue, I have no concern running it long-term.
