### ISSUE TITLE
Kubecost v1.97 doesn't work on K8S 1.25 (v1.98)

### ISSUE THREAD

**Issue by merlineus** [kubecost/cost-analyzer-helm-chart#1753] opened 2022-10-24 11:38 UTC
Hello. Seems that Kubecost doesn't support K8S 1.25.

**Describe the bug**  
After deployment cost-model fail it's readiness probe. In logs there is an error:
`E1024 09:07:56.918373       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.20.4/tools/cache/reflector.go:167: Failed to watch *v2beta1.HorizontalPodAutoscaler: failed to list *v2beta1.HorizontalPodAutoscaler: the server could not find the requested resource`
This is because starting from 1.25 **autoscaling/v2beta1** API is no longer supported and should be changed to **autoscaling/v2**
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125

**To Reproduce**  
1. Deploy latest Kubecost version from this repo to K8S 1.25 (we used GKE)
2. See logs of cost-model container

**Expected behavior**  
No errors in cost-model container logs and successful readiness probe.

**Screenshots**  
<img width="514" alt="Знімок екрана 2022-10-24 о 14 30 45" src="https://user-images.githubusercontent.com/410710/197516384-994ebb3e-7ccd-4e55-8ee0-791fb9fbde69.png">
<img width="1811" alt="Знімок екрана 2022-10-24 о 14 31 29" src="https://user-images.githubusercontent.com/410710/197516462-5812b6fb-05f3-455f-b50e-9a1143c87536.png">

I've searched through issues but didn't find a similar one, so creating this.

**Comment by AjayTripathy** [comment] 2022-10-24 14:35
Thanks for this @merlineus ! 
Here's the open issue: https://github.com/opencost/opencost/issues/1440

**Comment by merlineus** [comment] 2022-10-24 14:58
Thanks, @AjayTripathy, let's switch to the opencost issue, this could be closed probably.

**Comment by Adam-Stack-PM** [comment] 2022-10-24 15:01
@merlineus, For tracking with the engineering team, let's keep it open for now and I will once it is fixed. Thank you for the help.

**Comment by merlineus** [comment] 2022-10-24 15:12
Welcome. Do you have an ETA for fix?

**Comment by Adam-Stack-PM** [comment] 2022-10-25 20:27
@merlineus After researching this issue, the goal is to get this into v1.99, witch should be released around December 6th. 

@srpomeroy, Michael mentioned you may have some ideas on possible work arounds?

**Comment by michaelmdresser** [comment] 2022-10-25 20:46
Oh shoot, my bad here tagging in Sean P. This is actually a dupe of https://github.com/opencost/opencost/issues/1440. Sean has a workaround I think for a (separate) v1.25 issue that is specific to the Helm chart: PodSecurityPolicy removal. Sorry Adam!

**Comment by michaelmdresser** [comment] 2022-10-26 15:55
We now have an open PR that should resolve this issue: https://github.com/opencost/opencost/pull/1452.

@Adam-Stack-PM would you please help coordinate whether or not this change should be cherry-picked into the ongoing v1.98 release?

**Closed** 2022-10-26 16:11 UTC
Labels: bug, P0, v1.99

**Comment by michaelmdresser** [comment] 2022-10-26 16:16
PR for cherry-picking into v1.98 of Kubecost, if desired: https://github.com/opencost/opencost/pull/1453. My availability will be spotty for the rest of this week, so please feel free to close or merge that PR depending on if we want this fix in v1.98 of Kubecost.
