### ISSUE TITLE
docker hub image push

### ISSUE THREAD

**Issue by ywyt738** [kubecost/cost-analyzer-helm-chart#896] opened 2021-05-14 12:13 UTC
Please push kubecost image to dockerhub.

My network can't access to gcr.io

**Comment by dwbrown2** [comment] 2021-05-18 04:34
@ywyt738 it should be easy to self-host these from another repo that works for you. See here -- https://github.com/kubecost/docs/blob/master/air-gapped.md. Is that resource helpful? 

@AjayTripathy can you comment on the potential to cross-post in the future?

**Comment by AjayTripathy** [comment] 2021-05-26 05:42
I'd rather not officially support hosting these at more than one location at the free tier, since we'd have to maintain another account and pay or risk being rate limited which is a bad experience. Feel free to mirror from GCR to whatever private repos you'd like though.

**Comment by kirbsauce** [comment] 2021-07-30 16:39
Closing this issue for now, but please feel free to reopen if the issue is not resolved.

**Closed by kirbsauce** 2021-07-30 16:39 UTC
Labels: enhancement
