### ISSUE TITLE
GCP custom nodes pricing missing

### ISSUE THREAD

**Issue by dwbrown2** [kubecost/cost-analyzer-helm-chart#557] opened 2020-07-19 20:19 UTC
We had a user report that pricing is not being found for certain GCP custom nodes. Example cost-model logs below:

```
I0717 19:56:02.161038       1 costmodel.go:1143] [Warning] Error getting node pricing. Error: Warning: no pricing data found for &{map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/fluentd-ds-ready:true beta.kubernetes.io/instance-type:custom-1-1536 beta.kubernetes.io/masq-agent-ds-ready:true beta.kubernetes.io/metadata-proxy-ready:true beta.kubernetes.io/os:linux carol.ai/pool:c1.nano carol.ai/preemptible:true cloud.google.com/gke-nodepool:c1-nano-preemptible-1 cloud.google.com/gke-os-distribution:cos cloud.google.com/gke-preemptible:true cloud.google.com/metadata-proxy-ready:true cluster_name:prod-ai-1 failure-domain.beta.kubernetes.io/region:us-central1 failure-domain.beta.kubernetes.io/zone:us-central1-b kubernetes.io/arch:amd64 kubernetes.io/hostname:gke-prod-ai-1-c1-nano-preemptible-1-0f9bdec8-z63d kubernetes.io/os:linux node.kubernetes.io/masq-agent-ds-ready:true node_pool:c1-nano-preemptible-1 providerID:gce://labs-ai-apps-production/us-central1-b/gke-prod-ai-1-c1-nano-preemptible-1-0f9bdec8-z63d]}
```

```
I0710 18:02:34.024487       1 costmodel.go:1143] [Warning] Error getting node pricing. Error: Warning: no pricing data found for &{map[beta.kubernetes.io/arch:amd64 beta.kubernetes.io/fluentd-ds-ready:true beta.kubernetes.io/instance-type:custom-1-1536 beta.kubernetes.io/masq-agent-ds-ready:true beta.kubernetes.io/metadata-proxy-ready:true beta.kubernetes.io/os:linux carol.ai/pool:c1.nano carol.ai/preemptible:true cloud.google.com/gke-nodepool:c1-nano-preemptible-1 cloud.google.com/gke-os-distribution:cos cloud.google.com/gke-preemptible:true cloud.google.com/metadata-proxy-ready:true cluster_name:prod-ai-1 failure-domain.beta.kubernetes.io/region:us-central1 failure-domain.beta.kubernetes.io/zone:us-central1-b kubernetes.io/arch:amd64 kubernetes.io/hostname:gke-prod-ai-1-c1-nano-preemptible-1-0f9bdec8-sws5 kubernetes.io/os:linux node.kubernetes.io/masq-agent-ds-ready:true node_pool:c1-nano-preemptible-1 providerID:gce://labs-ai-apps-production/us-central1-b/gke-prod-ai-1-c1-nano-preemptible-1-0f9bdec8-sws5]}
```

reported by Carlos

**Comment by AjayTripathy** [comment] 2020-07-21 00:43
This is potentially caused by requiring a pod restart to pick up new types. That is fixed in https://github.com/kubecost/cost-model/pull/478

**Closed** 2020-07-26 23:30 UTC
Labels: bug
