### ISSUE TITLE
Cannot parse JWT id_token: failed to match any of the keys for OIDC Authentication

### ISSUE THREAD

**Issue by praveenkumar0566** [kubecost/cost-analyzer-helm-chart#2163] opened 2023-04-19 18:35 UTC
---
# For reproducible bugs, please provide the following
Enable OIDC 

**Describe the bug**  
It seems that OIDC authentication works when RBAC is disabled
When RBAC enabled, authentication fails as shown in these log lines. Likely due to parseJWT function

[90m2023-04-12T19:28:18.488514549Z[0m [32mINF[0m Attempting to authenticate oidc...
[90m2023-04-12T19:28:18.488578488Z[0m [32mINF[0m Validating OIDC token...
[90m2023-04-12T19:28:18.488590484Z[0m [32mINF[0m Attempting to fetch token from cookie...
[90m2023-04-12T19:28:19.163867844Z[0m [32mINF[0m 200 for request GET https://-----/userinfo HTTP/1.1 in cookie or header
[0m Attempting to fetch token from cookie...
WRN[0m Cannot parse JWT id_token: failed to match any of the keys
INF[0m Authentication failed, writing 401...

**To Reproduce**  
Setup OIDC in v1.102.0 and v1.102.1
**Expected behavior**  
OIDC with RBAC should work

**Screenshots**  
Will be shared through direct chat.

**Collect logs (please complete the following information):**
More logs and screenshot can be shared directly over slack due to security concern.

**Comment by kwombach12** [comment] 2023-04-19 18:42
@teevans can you help triage this?

**Comment by teevans** [comment] 2023-04-21 15:44
@praveenkumar0566 -  Can you setup a repro environment? @kaelanspatel will be back monday and will have some time to work on it then

**Comment by kirbsauce** [comment] 2023-04-21 15:53
@teevans , @praveenkumar0566 is on holiday, back 4/30.

**Comment by praveenkumar0566** [comment] 2023-05-02 14:47
Copying the investigation done by @biancaburtoiu 


Hi team! I got some time to investigate into this issue. The error I have tracked here is Cannot parse JWT id_token: failed to match any of the keys which stems from the RBAC groups validation within the OIDC token validation flow.

The root cause here appears to be a mismatch between the ID token and the JWKS public keys required to validate said token. Based on the code in the [JWKS go library][](https://github.com/lestrrat-go/jwx/blob/4b1993570c9814728e7d18df821f6925d45a3ad0/jwt/jwt.go#L202, I have reason to believe that we can find the key (line 237) but we skip the checks on line 261 and 271, to then return the error on line 291.

We store JWKS keys inside the oidcData.OIDCMetadata.JWKsURL variable. Note that the OIDC metadata values are logged when initialising the application, so by tracking the log:
[90m2023-04-12T19:26:50.150702154Z[0m [32mINF[0m Configured OIDC with metadata: 
 {TokenURL:<https://login.microsoftonline.com/2b69d099-dc61-447b-84c8-001733d8be3a/oauth2/v2.0/token> IntrospectURL: UserinfoURL:<https://graph.microsoft.com/oidc/userinfo> LogoutURL:<https://login.microsoftonline.com/2b69d099-dc61-447b-84c8-001733d8be3a/oauth2/v2.0/logout> JWKsURL:<https://login.microsoftonline.com/2b69d099-dc61-447b-84c8-001733d8be3a/discovery/v2.0/keys>}
we can observe that the JWKsURL is [](https://login.microsoftonline.com/2b69d099-dc61-447b-84c8-001733d8be3a/discovery/v2.0/keys)

Accessing this (public) URL will show a list of key objects. Several aspects to note:
the kid field of one of these keys matches the kid field of the header of the decoded JWT ID tokens, as extracted from the container logs and decoded via [jwt.io](https://jwt.io/)
none of these keys contain an alg field ← I suspect this is the main problem
 
The JWT/JWKs library documentation advises that users fix their keys so that they contain an alg header. I don’t have much expertise with these validation mechanisms but from what I understand here, JWK keys normally do come with an alg field, which makes it strange that in this particular case we don’t have it.

After googling some more I'm finding that Microsoft doesn't add this field to the JWK keys. Maybe we could dig into this a bit more and see if there's any way we can customize the JWKS output on the Microsoft integration side so that the keys could actually come with the alg field we need? 
 
Other users seem to have worked around this by inferring the algorithm from the JWT token instead of the JWKS key. If the idea above doesn't work, we might need to implement a similar workaround.

**Comment by vranyes** [comment] 2023-05-09 20:34
I'm seeing this same behavior as well: OIDC login works when `oidc.rbac.enabled: false` but breaks with the same error when `true`. I'm using Azure AD OIDC provider and `claimName: roles`. It doesn't look like the documentation is up-to-date with this feature either, and the defaults in the `values.yaml` don't align with what the oidc configmap template expects to iterate over...

**Comment by kennethredler** [comment] 2023-05-09 23:47
Any help with this @praveenkumar0566 @teevans @kaelanspatel @kwombach12 ❓

**Comment by teevans** [comment] 2023-05-10 17:21
@praveenkumar0566 - Can you put together a repro environment for us?

**Comment by kennethredler** [comment] 2023-05-15 14:01
Anything we can do to support your inquiry on this issue @teevans / @praveenkumar0566 ❓

Thanks for the help!

**Comment by thomasvn** [comment] 2023-05-15 19:29
@kennethredler @teevans I've got this reproduced and am investigating now.

**Comment by thomasvn** [comment] 2023-05-18 15:15
Quick update here. I have a fix for this issue that's currently under review. This fix will likely be in v1.104

**Comment by kennethredler** [comment] 2023-05-24 02:21
Any ETA on v1.104 @thomasvn ?

**Comment by thomasvn** [comment] 2023-05-26 00:15
@kennethredler Code not merged yet, but I anticipate it will be merged soon. Once merged, it should be available in the [nightly release](https://docs.kubecost.com/architecture/release-process#nightly-releases) and in v1.104 (expected release date June 6th)!

Additionally, here is some preliminary documentation
https://github.com/kubecost/poc-common-configurations/tree/main/oidc-azuread

**Closed as completed** 2023-06-02 16:21 UTC
Labels: bug, needs-triage

**Comment by thomasvn** [comment] 2023-06-02 16:51
As an update, v1.104 will include a fix to this immediate problem,

```
Cannot parse JWT id_token: failed to match any of the keys
```

however full support for AzureAD OIDC RBAC will not be making it into v1.104. A bit more work needs to be done on my end to refactor the code because of the unique way AzureAD is implementing the OIDC protocol.

**Comment by kennethredler** [comment] 2023-06-13 02:01
> As an update, v1.104 will include a fix to this immediate problem,
> 
> ```
> Cannot parse JWT id_token: failed to match any of the keys
> ```
> 
> however full support for AzureAD OIDC RBAC will not be making it into v1.104. A bit more work needs to be done on my end to refactor the code because of the unique way AzureAD is implementing the OIDC protocol.

Thanks again for the quick fix.

Does the AzureAD OIDC work you've identified here 👆 have an issue or release we could follow and upvote, @thomasvn ? 😄

**Comment by thomasvn** [comment] 2023-06-13 21:06
@kennethredler Not yet, would you be willing to create one? I'll assign to myself once created!

**Comment by kennethredler** [comment] 2023-06-15 18:23
@thomasvn 👉 https://github.com/kubecost/cost-analyzer-helm-chart/issues/2368 👈
